### ISSUE TITLE
Ability to override default server port with the PORT env var

### ISSUE THREAD

**Issue by Rush** [deepkit/deepkit-framework#104]
Not a big deal but ... given the example in https://deepkit.io/documentation/framework as a user of Deepkit I would like to be able to override the default app port.
```
PORT=8081 ts-node-script app.ts server:listen
```

**Comment by marcj** [comment]
All configuration options can be overwritten via env variables once activated. See https://deepkit.io/documentation/framework/configuration#configure-module
```
Application.create({
      //...
})
    .loadConfigFromEnvVariables('APP_') //<-- important
    .run();
````

then you can overwrite options from the kernel module (where the port is specified):

```
APP_kernel_config=8081 ts-node app.ts server:listen
```

You can see all configuration options via `ts-node app.ts app:config`

**Comment by ZPiDER666** [comment]
just in case anybody find this useful: here is a more recent version of above answer:

before app.run() do this:

    app.loadConfigFromEnv({ prefix: 'APP_' })

and right before your call to start the app do this:

    export APP_FRAMEWORK_PORT=8083;

note the uppercase!
