### ISSUE TITLE
support Map()

### ISSUE THREAD

**Issue by colorcube** [deepkit/deepkit-framework#106]
It would be nice if Map() could be used as a type with plainToClass/classToPlain

I tried this, which gives me an empty object.

```
    @t.map(MyInfoClass)
    mymap = new Map<string, MyInfoClass>();
```

I guess @t.map() is meant to be used for plain objects?

Any advice is welcome

**Comment by marcj** [comment]
Yeah, had this on the list for quite some time. Currently t.map means actually an object like `{[name: string]: number}`, but that is semantically wrong. We should rename that to `t.record` or `t.object` and make `t.map` a real `Map`.

**Comment by colorcube** [comment]
Thanks for the clarification.

t.record sounds good to me. 
t.object might be more misleading?

**Comment by WonderPanda** [comment]
I think `t.record` sounds better here as well

**Comment by marcj** [comment]
this is now supported in master with the new runtime type system.
