### ISSUE TITLE
Getting `ObjectId()` instance from the BSON parser.

### ISSUE THREAD

**Issue by theodorDiaconu** [deepkit/deepkit-framework#108]
My use-case is very specific, I do care about the fact that if I have a `t.mongoId` after I run a BSON decoding using `@deepkit/bson`, to get an actual ObjectId(). I understand that bson decodes ObjectIds as string, but what would be, in your opinion the most efficient way to achieve my goal?

The only way I could think of right now is to parse the schema, see where I have objects run through the results and instantiate it myself. 

Thanks!

**Comment by marcj** [comment]
`ObjectId` from the `mongodb`/`bson` package and is just one representation of the mongo id. Another is binary array or a hex string. @deepkit/bson does not use the `mongodb` package and thus has no `ObjectId`. It's not necessary to wrap that in a class like `ObjectId`. If you want for whatever reason to have a ObjectId instead, you can write your [own serializer](https://deepkit.io/documentation/type/serialization-target#extend-a-serializer) and overwrite the type 'objectId'. But then you have the `mongodb` or `bson` package as dependency.

**Comment by theodorDiaconu** [comment]
Thanks for your response!
I will look in having a serializer, what I did now is stupid:

```ts
  protected cleanResults(results) {
    this.schema.getProperties().forEach((property) => {
      const name = property.name;
      if (property.type === "objectId") {
        for (const result of results) {
          result[name] = new ObjectId(result[name]);
        }
      }
      if (
        property.type === "array" &&
        property.getSubType().type === "objectId"
      ) {
        for (const result of results) {
          result[name] = result[name].map((id) => new ObjectId(id));
        }
      }
      if (property.type === "date") {
        for (const result of results) {
          result[name] = new Date(result[name]);
        }
      }
    });
  }
```

I shall look into the Serializer thingie. Thanks, I will close the issue since for me it's clear.

**Comment by theodorDiaconu** [comment]
```
const mySerializer = new Serializer("custom serializer");
mySerializer.toClass.register("date", (property, compiler) => {
  compiler.addSetter(`new Date(${compiler.accessor})`);
});
mySerializer.toClass.register("objectId", (property, compiler) => {
  // I tried this not sure if it's ok tells me require is not defined
  compiler.addCodeForSetter('const ObjectId = require("mongodb").ObjectId');
  // like this it ofcourse tells me ObjectId not defined
  compiler.addSetter(`new ObjectId(${compiler.accessor})`);
});
```

Do you have any mechanism of importing other objects?
