### ISSUE TITLE
(deepkit/bson) cjs compilation not up to date?

### ISSUE THREAD

**Issue by theodorDiaconu** [deepkit/deepkit-framework#112]
```
const crypto = __importStar(require("@deepkit/crypto"));
```

`node_modules/@deepkit/bson/dist/cjs/src/model.js`

^ Inside the dist of latest alpha 35.

However I see no such thing in the `model.ts` file. This error I only get in production.

**Comment by marcj** [comment]
I don't see an error in your post?

**Comment by theodorDiaconu** [comment]
It's related again the npm 6 and peerDependencies. Not an issue here, sorry

**Comment by theodorDiaconu** [comment]
So, the problem wasn't intuitive, because I have used "@deepkit/bson" in a separate package to leverage its goodness, but basically in that package I need to add additional "dependencies" (core, type, crypto), I needed to manually add them to work within a deployment inside creative cloud. But I don't think there's anything to do on your counter-part for npm 7

Is there any  particular reason  you chose peerDependencies vs dependencies ?

**Comment by marcj** [comment]
Yes, it makes handling dependencies easier for me, makes it safer for the user (so no npm dupes happen), and nominal types work correctly.
