### ISSUE TITLE
Dynamic app modules

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#119]
I know the documentation isn't exactly considered finished.
https://deepkit.io/documentation/framework/modules

From what I can see, you have to create the config inline, providing no way for users to define the configuration required for the module.

In NestJS this is easily doable with [dynamic modules](https://docs.nestjs.com/fundamentals/dynamic-modules#dynamic-module-use-case).

How would one be able to do something similar with this framework instead?

**Comment by marcus-sa** [comment]
Maybe the instantiation and usage of modules could be similar to NestJS?

**Comment by marcj** [comment]
Dynamic modules are possible by simply calling "new AppModule". A user can also change configuration, by calling on the module ".configure({option: value})".
