### ISSUE TITLE
conditional validation

### ISSUE THREAD

**Issue by timc13** [deepkit/deepkit-framework#132]
Is there support for conditional validation based on a sibling property? Something like https://github.com/typestack/class-validator#conditional-validation

**Comment by marcj** [comment]
No, not yet. Conditional validation is only available in the Angular Forms plugin from deepkit/type.

**Comment by timc13** [comment]
Currently you allow custom validation - but only based on the local value.  I think generally, an approach to customize validation based on the whole data object would allow something like this to be built in a "plugin"-able fashion.  I think zod does this well with https://github.com/colinhacks/zod#refine

**Comment by marcj** [comment]
Yes, we can certainly pass the whole parent object of a property to its validator. This would allow conditional validation at least in the way that you can manually check sibling properties. Would this satisfy your use-case?

**Comment by timc13** [comment]
yes!

**Comment by marcj** [comment]
This is supported now on classes in master:

```typescript
    class Email {
        constructor(public email: string) {
        }

        @t.validator
        validator(): ValidatorError | void {
            if (this.email === '') return new ValidatorError('email', 'Invalid email');
        }
    }

    expect(validate<Email>(new Email(''))).toEqual([{ path: '', code: 'email', message: 'Invalid email' }]);
    expect(validate<Email>(new Email('asd'))).toEqual([]);
```
