### ISSUE TITLE
NPM isn't doing the type library justice.

### ISSUE THREAD

**Issue by smolinari** [deepkit/deepkit-framework#137]
Hi,

It seems the readme doesn't translate to be shown on NPM properly for @deepkit/type. Just thought I'd bring it to your attention. 

![image](https://user-images.githubusercontent.com/3314957/131511698-1428ad85-cf38-48ae-a5bc-5094833eff73.png)

Scott

**Comment by marcj** [comment]
Works for me. You need to open the first the "Readme"

<img width="1430" alt="Screenshot 2021-08-31 at 16 38 34" src="https://user-images.githubusercontent.com/450980/131522784-561d9ef2-6af5-47e1-83ed-35a727abde80.png">

**Comment by smolinari** [comment]
Oh Duh! Sorry about that. Silly me. 😊 

Scott

**Comment by smolinari** [comment]
Wonder why it opened up with that "Discover" tab? Ok. Nevermind. 😁 

Scott
