### ISSUE TITLE
 Type JSONEntity has no call signatures.ts

### ISSUE THREAD

**Issue by mwj-1992** [deepkit/deepkit-framework#146]
I have this :`const IUPlans=  JSONEntity<SuppOffer[]>;`
and trying to loop over this array but keep getting that no call signatures while looping 
`IUPlans.map((item: any) => OfferMapper.toDomain(item));`
if ive removed JSONENTITY everything goes well, but have to keep it to not impact other code parts

Does anyone have any idea how to deal with this issue?

**Comment by marcj** [comment]
```typescript
const IUPlans= JSONEntity<SuppOffer[]>;
```

That's not valid TypeScript code. Also please use Github discussion for support requests. This is the issue tracker.
