### ISSUE TITLE
OpenAPI Support

### ISSUE THREAD

**Issue by ayuhito** [deepkit/deepkit-framework#147]
I heard it was planned within the Discord, but I'm just making an issue to make things easier to track. :)

**Comment by ctfrancia** [comment]
is there some update?

**Comment by hanayashiki** [comment]
Looking forward to that

**Comment by hanayashiki** [comment]
I've made one myself! Please take a look to see if it satisfy your needs:
https://github.com/hanayashiki/deepkit-openapi

It is still under development and needs improvement ~

**Comment by marcj** [comment]
Closing since @hanayashiki provides already a very well working Deepkit OpenAPI integration
