### ISSUE TITLE
[orm] Mapping column names?

### ISSUE THREAD

**Issue by icopp** [deepkit/deepkit-framework#150]
For a very simple case, let's say I have:

```js
@entity.name('order')
export default class Order {
  @t.primary.uuid.required
  id!: string

  @t.uuid.required
  someId!: string
}
```

How do I map `someId` there to a column name of `some_id` in the database?

**Comment by timvandam** [comment]
I don't think its possible yet, but it is planned: https://github.com/deepkit/deepkit-framework/projects/1#card-67722965

**Comment by marcj** [comment]
This is possible in the newest version using `MapName` https://docs.deepkit.io/english/runtime-types.html#_mapname
