### ISSUE TITLE
findOne with relation issue

### ISSUE THREAD

**Issue by Paula2001** [deepkit/deepkit-framework#160]
findOne with many to many relation returns one entity for the relation and not many and also return one entity of the original relation which is right

Example : Car have many passengers .

Car -> [p1,p2,p3] This should be the result 
Car -> [p3] Put this what I get

**Comment by timvandam** [comment]
i have this listed in #152 (5) too
for now you will just need to do two queries (or `.find().then(results => results[0])`)

**Comment by Paula2001** [comment]
okay thanks
