### ISSUE TITLE
Module resolution errors

### ISSUE THREAD

**Issue by lionelhorn** [deepkit/deepkit-framework#161]
I have a NextJs app inside a monorepo. Pacakges are built using [Nx](https://nx.dev/)

**package.json**
```
"dependencies": {
    "@deepkit/type": "^1.0.1-alpha.58",
    [...]
}
```

**Yarn install log**
```
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @deepkit/type@1.0.1-alpha.58" has unmet peer dependency "@deepkit/core@^1.0.1-alpha.13".
warning " > @deepkit/type@1.0.1-alpha.58" has unmet peer dependency "reflect-metadata@^0.1.13".
[...]
```

I try to build 
``` 
nx build
````

I get
```
../../node_modules/@deepkit/type/dist/esm/src/decorators.js
Module not found: Can't resolve '@deepkit/core' in '[path-omitted]\node_modules\@deepkit\type\dist\esm\src'
``` 

Looking at the yarn log, I then see that It's messing a peer dependency to 
"@deepkit/core@^1.0.1-alpha.13"
"reflect-metadata": "^0.1.13"

So I added those.

Then the build error becomes
``` 
Cannot find module '[path-omitted]\node_modules\@deepkit\type\dist\esm\src\types' imported from [path-omitted]\node_modules\@deepkit\type\dist\esm\index.js

Any ideas?

**Comment by marcj** [comment]
Do the files in `node_modules\@deepkit\type\dist\esm\src` exist?

**Comment by lionelhorn** [comment]
``` node_modules\@deepkit\type\dist\esm\src``` exists.

Can the layout of the monorepo be an issue?
There is only one ```node_modules``` and one package.json for the whole repo at the root level and Nx is supposed to detect the dependency used by each package.

```
├───apps
│   ├───kds
│   │   ├───src
│   │   │   ├───components
│   │   │   ├───core
│   │   │   │   ├───data
│   │   │   │   ├───orders
│   │   │   │   ├───transform
│   │   │   │   └───ui
│   │   │   ├───styles
│   │   │   ├───utils
│   │       └───views
├───libs
│   └───shared
│       └───src   
├───node_modules
│   ├───@deepkit
│   │   ├───core
│   │   │   ├───dist
│   │   │   │   ├───cjs
│   │   │   │   │   ├───src
│   │   │   │   │   └───tests
│   │   │   │   └───esm
│   │   │   │       ├───src
│   │   │   │       └───tests
│   │   │   ├───node_modules
│   │   │   │   └───to-fast-properties
│   │   │   ├───src
│   │   │   └───tests
│   │   └───type
│   │       ├───dist
│   │       │   ├───cjs
│   │       │   │   └───src
│   │       │   └───esm
│   │       │       └───src
│   │       └───node_modules
│    package.json   
```

**Comment by marcj** [comment]
Does your tree structure mean there are no files at all in it? It looks for a file `node_modules\@deepkit\type\dist\esm\src\types.js`. is this available?

**Comment by lionelhorn** [comment]
Yes, the ```node_modules\@deepkit\type\dist\esm\src\types.js``` is present

What I tried to illustrate in the tree, is that there no separate ```node_modules``` for each "package".

<img src="https://user-images.githubusercontent.com/50528276/144106321-087146e4-7a23-4ed1-8d7b-b1498432a38e.png" width="250">

**Comment by marcj** [comment]
That's fine. I use monorepos all the time, so that shouldn't be a problem. So the file exists but your build tool complains it does not exist. This is unfortunately not related to deepkit as the only thing we need to make sure is that the files are available and they correctly import each other. Anything else is up to the build tool.

Does `node_modules\@deepkit\type\dist\esm\index.js` have the correct import to the `type` file?

**Comment by lionelhorn** [comment]
Nx calls nextjs build tool 
So I get the same error using 
```npx next build```

If I understood your question correctly

```node_modules\@deepkit\type\dist\esm\index.js```
``` 
export * from './src/types';
```

**Comment by marcj** [comment]
Ok, that code looks fine. So, it seems you installed all the packages correctly and the files are correct. At this point, I can't help further as I have no idea how next builds the stuff and how to debug that error using it. I'd probably try to modify the file `node_modules\@deepkit\type\dist\esm\index.js` a bit and check if that has any implication and if so which one (so to check if that is really the actual read/used file for example)

**Comment by lionelhorn** [comment]
Thanks.
I really appreciate the pointers on how to fix the issue :) !

On a side note, I see this project is using Lerna.
Have you used others in the past or thinking of migrating to others?

I've seen Lerna isn't actively maintained anymore.
https://github.com/lerna/lerna/issues/2703#issuecomment-744601134

**Comment by marcj** [comment]
> Have you used others in the past or thinking of migrating to others?

Yeah, was thinking about using Rush from Microsoft, but nothing concretely planned. Lerna works well for the moment still. :)

**Comment by lionelhorn** [comment]
I posted the issue at https://github.com/vercel/next.js/issues/31974

**Comment by lionelhorn** [comment]
Could you have a look at 
https://github.com/vercel/next.js/issues/31974#issuecomment-983041963

**Comment by marcj** [comment]
TypeScript's compiler does not support Node's default ESM resolution algorithm. They have introduced t in version 4.5 beta https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs, but dropped it in the final 4.5 due to issues. To enable the commonly used module resolution algorithm you have to pass to node `--experimental-specifier-resolution=node`. You can also configure that in your environment variable `NODE_OPTIONS=--experimental-specifier-resolution=node`

**Comment by productdevbook** [comment]
some problem next 12

and dont fixed -> NODE_OPTIONS=--experimental-specifier-resolution=node

![image](https://user-images.githubusercontent.com/38668796/161917259-af8963fe-cb74-491a-90df-62821c7cd978.png)

**Comment by JumpLink** [comment]
I think it would help to add the `.js` on all internal imports to fix the ESM Packages

**Comment by marcj** [comment]
We added already a lot of .js file extension in our imports, not all are covered yet though

**Comment by JumpLink** [comment]
@marcj Okay, here a MR #302 to add the missing file extensions, too :)

**Comment by productdevbook** [comment]
if that means it will work with nuxt 3 as well ?
