### ISSUE TITLE
Custom convertors for properties

### ISSUE THREAD

**Issue by s888** [deepkit/deepkit-framework#18]
Hi,
I have certain properties in class which should be an integer.
So is it possible to write custom converters that would convert a value to Integer during plainToClass?

Say for example:
```
class MyCustomConvertor implements PropertyValidator {
    validate<T>(value: any): PropertyValidatorError {
          return Math.trunc(value)
    };
}
class SimpleModel {
@f.validator(MyCustomConvertor)
    type: number
}

const instance = validatedPlainToClass(SimpleModel, {id:1.1});
console.log(instance) //instance.id will be 1
```

**Comment by marcj** [comment]
Not yet, but would be a good feature. It needs some more definition though because there are open questions and performance implication when allowing to modify the actual value during plainToClass:

1. Validation happens before plainToClass is called, which means all those modifications need to apply during validation temporarily as well.
2. What is called first during validation: custom validator, internal validators (array check, string/number, etc), or modifications? In which order?
3. Is it allowed to modify the passed object in-place by those modifier or is it necessary to create a temporary container?
4. During plainToClass: Are these custom modifier called before calling internal modifier, or after? Should a user be able to choose the behavior?

**Comment by s888** [comment]
> Not yet, but would be a good feature. It needs some more definition though because there are open questions and performance implication when allowing to modify the actual value during plainToClass:
> 
>     1. Validation happens before plainToClass is called, which means all those modifications need to apply during validation temporarily as well.
> 
>     2. What is called first during validation: custom validator, internal validators (array check, string/number, etc), or modifications? In which order?
> 
>     3. Is it allowed to modify the passed object in-place by those modifier or is it necessary to create a temporary container?
> 
>     4. During plainToClass: Are these custom modifier called before calling internal modifier, or after? Should a user be able to choose the behavior?

Thanks for the reply.
Is there an ETA for this?

**Comment by marcj** [comment]
No, there's no ETA yet.

**Comment by Rush** [comment]
I second this request. This would allow to provide a replacement path for `class-transformer` users and also allow Nest to mention this library as an alternative to `class-transformer`. While @marcj I know that  your request to Nest was rejected, I think matching the functionality of `class-transformer` would go a long way.

**Comment by Rush** [comment]
btw. Here is a partial workaround if you're transforming to a different property name:
```ts
@t.type(String)
get thumbnailUrl() {
  return `/${idToString(this._id)}.thumbnail?${new Date(this.updatedAt).getTime()}`;
 }
```
Of course if `thumbnailUrl` was an existing property this wouldn't work.

**Comment by marcj** [comment]
Transformation from class to x (serialization) is now implemented via `@t.transform`, however a normalization step during x to class (deserialization) is not yet available.

e.g.

```typescript
class User {
    @t id: number;
}

class Product {
     @t id: number;

     constructor(
       @t.transform((user: User) => user.id)
       owner: User
   ){}
}

const plain = classToPlain(new Product(new User())); //{owner: 1234}
```

**Comment by marcj** [comment]
I implemented the full feature now. See https://github.com/deepkit/deepkit-framework/blob/1c9094844821d9eb049332a83c69e80347f5472a/packages/type/tests/transform.spec.ts for examples.

and the API:
https://github.com/deepkit/deepkit-framework/blob/1c9094844821d9eb049332a83c69e80347f5472a/packages/type/src/field-decorator.ts#L125-L162
