### ISSUE TITLE
chore: improve the `repository` entry on `package.json` to follow the monorepo structure

### ISSUE THREAD

**Issue by micalevisk** [deepkit/deepkit-framework#191]
For instance, if you change this:

https://github.com/deepkit/deepkit-framework/blob/9ca56a0f1c075f392118628e3b97ca2a958a4216/packages/type/package.json#L22

to this:

```
  "repository": {
    "url": "https://github.com/deepkit/deepkit-framework",
    "directory": "packages/type"
  },
```

then the _repository_ link on NPM website will bring us to the `./packages/type` dir

**Comment by marcj** [comment]
Oh awesome, will do it👍

**Comment by micalevisk** [comment]
closing this due to inactive
