### ISSUE TITLE
[Feature] Support Resolution of the Exact tsconfig File

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#212]
Currently `@deepkit/type-compiler` reads `tsconfig.json` only, ignoring the true tsconfig file used for execution or compilation, which might be `tsconfig.build.ts` or `tsconfig.app.ts`.

This behavior might force us to mess up the responsibility of each tsconfig file. It would be better to support resolution of the exact tsconfig file.

**Comment by marcj** [comment]
We do not have any information in TypeScript transformers about the build. It could be a `tsc` or a Project References build via `tsc --build`. Thus, there is no way to correctly determine which tsconfig is actually the correct one for a particular file.

**Comment by marcj** [comment]
Implemented in https://github.com/deepkit/deepkit-framework/commit/bb2ac7e4e1a2bdec20e149f0f58d55b817a571a2
