### ISSUE TITLE
[Bug] mixture of lockfileVersion: 2 and lockfileVersion: 1

### ISSUE THREAD

**Issue by hanayashiki** [deepkit/deepkit-framework#242]
I found this project is compatible with npm@6, which has ["lockfileVersion": 1](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion) in most of the subprojects. However, I found these two package-lock.json using `lockfileVersion: 2`

<img width="306" alt="image" src="https://user-images.githubusercontent.com/26056783/170907031-733411a7-a5d9-46a0-91ab-f9d14bca857e.png">

I wonder it is a leak from higher version of npm. If so, I think it's better to:

1. update all lockfile version to latest
2. keep lockfile version the same if that's for some other reasons

Thank you

**Comment by TheNightmareX** [comment]
This is a known issue and will be fixed in the future. It is because thie project uses Lerna for package management, which depends on a different npm version.

**Comment by marcj** [comment]
Fixed in master
