### ISSUE TITLE
`loosely` parameter in `cast()` doesn't seem to work

### ISSUE THREAD

**Issue by kerberjg** [deepkit/deepkit-framework#262]
Hi, based on what the documentations seems to indicate, when `loosely` is set to false, it should disable implicit type conversion and throw an error when a type doesn't match. However it does not seem to work:

```ts
import { cast } from '@deepkit/type';

interface Data {
    id: number;
    name: string;
}

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const d = cast<Data>({id: '', name: 1}, { loosely: false });

console.log(d);
```

Returns: `{ id: 0, name: '1' }`
Expected: `ValidationError`

**Comment by marcj** [comment]
Good catch, it was currently only used for union types and was disabled by default. I enabled it now per default and throws for primitives. Fixed in https://github.com/deepkit/deepkit-framework/commit/55a8a5628c68ebe3656604679d7304e13da53107

**Comment by kerberjg** [comment]
Thank you, great job! It works just fine 😊

**Comment by marcj** [comment]
no problem. cool glasses✌️
