### ISSUE TITLE
[BUG]: Email validator doesn't work

### ISSUE THREAD

**Issue by hanayashiki** [deepkit/deepkit-framework#263]
```
import { Email, validate } from "@deepkit/type";

console.log(validate<string & Email>('xxxx'));
```

Expected: return an error about 'xxxx' not being an email.

Acutal: no error is returned

Versions
```json
{
    "@deepkit/type": "^1.0.1-alpha.71",
    "@deepkit/type-compiler": "^1.0.1-alpha.71"
}
```

**Comment by marcj** [comment]
We've unit tests that cover that: https://github.com/deepkit/deepkit-framework/blob/30939492b96fd90d027728fc7a3030e8d8d24bf3/packages/type/tests/validation.spec.ts#L16

It should be `validate<Email>` as Email is already a string.

**Comment by TheNightmareX** [comment]
maybe `string & Email` should be better treated the same as type `Email` in the runtime type system?

`string & string & SomeDecoration` should be the same type as `string & SomeDecoration`
