### ISSUE TITLE
[BUG]  AutoCrud PUT method input should be of type HttpBody

### ISSUE THREAD

**Issue by rogrdat** [deepkit/deepkit-framework#265]
the line -- 
`    async update(id: IdentifierType, body: Partial<SchemaType>) { `
should be 
`    async update(id: IdentifierType, body: HttpBody<Partial<SchemaType>>) { `

**Comment by marcj** [comment]
Good catch. Care to create a pull-request? :)

**Comment by marcj** [comment]
This is released in https://github.com/deepkit/deepkit-framework/releases/tag/v1.0.1-alpha.72
