### ISSUE TITLE
[Feature] Declarative ORM Events using `@deepkit/event`

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#269]
> This is already in progress. Open an issue here only for progress tracking.

The current ORM event system doesn't use `@deepkit/event` because its built before `@deepkit/event`, thus we cannot listen to these ORM events conveniently when using the framework.

Current event API:

```ts
database.unitOfWorkEvents.onInsertPre.subscribe()
```

**Comment by marcj** [comment]
The following API is in line with the other listener APIs:

```typescript
database.listen(UnitOfWorkEvents.onInsertPre, (event) => {})
```

Needs probably also an unsubscribe functionality

**Comment by marcj** [comment]
Fixed in master.

**Comment by marcj** [comment]
This is released in https://github.com/deepkit/deepkit-framework/releases/tag/v1.0.1-alpha.72
