### ISSUE TITLE
Config injection improvement

### ISSUE THREAD

**Issue by NexZhu** [deepkit/deepkit-framework#274]
Given config like this:

```ts
export class HelloConfig {
  title: string = 'World'
  color: string = 'yellow'
  year: number = 2022
}

export class Config {
  hello: HelloConfig = new HelloConfig()
}
```

Currently injecting works this way:
```ts
@cli.controller('test')
export class TestCommand implements Command {
  constructor(
    protected config: Config['hello'],
  ) {}
}
```

But it doesn't work this way, although `HelloConfig` and `Config['hello']` is the same type:
```ts
@cli.controller('test')
export class TestCommand implements Command {
  constructor(
    protected config: HelloConfig,
  ) {}
}
```

Will give me this error:
```
DependenciesUnmetError: Undefined dependency "config: any" of TestCommand(?). Type has no provider in scope cli.
```

Can we support injecting directly using `HelloConfig` like the above code? Otherwise, suppose we have a deeply nested config, we will have to write something like `Config['fieldA']['fieldB']['fieldC']` to inject the needed config class.

This config module for Nest.js is an example:
https://github.com/Nikaple/nest-typed-config

It supports injecting any sub-config:
```ts
@Injectable()
export class AppService {
  // inject any config or sub-config you like
  constructor(
    private config: RootConfig,
    private databaseConfig: DatabaseConfig,
    private tableConfig: TableConfig,
  ) {}
}
```

**Comment by NexZhu** [comment]
Another question, how to set for example `config.hello.title` from the environment variable? I didn't see the example in the docs:
https://deepkit.io/documentation/framework/configuration

I would imagine something like `APP_HELLO_TITLE=Jack` but it's not working.

https://github.com/Nikaple/nest-typed-config has an option to set the separator (defaults to `__`), so we can set `HELLO__TITLE`, `HELLO__COLOR`, `HELLO__YEAR`

**Comment by marcj** [comment]
The configuration injection needs always a reference to the real used configuration class. So, by defining a dependency `protected config: HelloConfig` where `HelloConfig` is not the configuration object, the system is not able to inject it as there is not relation known to `Config`. You have to use the notation `protected config: Config['hello'],` instead.
