### ISSUE TITLE
validate only returns first error

### ISSUE THREAD

**Issue by rjurado01** [deepkit/deepkit-framework#287]
When I check [documentation](https://docs.deepkit.io/english/validation.html#validation-usage) I see that validate should returns an array of errors for diferent properties:

```js
// code from doc

import { validate } from '@deepkit/type';

interface User {
    id: number;
    username: string;
}

...

validate<User>({}); // <- HERE IS THE BUG !!
//[
//  {path: 'id', code: 'type', message: 'Not a number'}],
//  {path: 'username', code: 'type', message: 'Not a string'}],
//]
```

![image](https://user-images.githubusercontent.com/1703608/192159799-bfe071f6-af0e-4610-9f81-0d566755b0f1.png)

But when I execute this code, I only get first error:

```
[
  ValidationErrorItem {
    path: 'id',
    code: 'type',
    message: 'Not a number'
  }
]
```

I expect:

```
[
  ValidationErrorItem {
    path: 'id',
    code: 'type',
    message: 'Not a number'
  },
  ValidationErrorItem {
    path: 'username',
    code: 'type',
    message: 'Not a string'
  }
]
```

I'm using: `"@deepkit/type": "^1.0.1-alpha.75"`

**Comment by marcus-sa** [comment]
What about `validates`?

**Comment by rjurado01** [comment]
> What about `validates`?

According to the documentation the correct method to get an array of errors is `validate`.

![Screenshot_20220708_083726](https://user-images.githubusercontent.com/1703608/177932020-c844107e-46cd-4a79-b8ed-65208ab81012.png)

`validates` returns a boolean.

**Comment by marcj** [comment]
Thanks for the report, fixed in https://github.com/deepkit/deepkit-framework/commit/7e965bd9bafe437e6a5340c1c3b22360b50d1ed7
