### ISSUE TITLE
Reusable validator types doesn't work in interfaces

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#290]
I'm trying to create a reusable type for validation by combining built-in validators as shown below:
```ts
export type PercentageMultiplier = number &
  Decimal<0, 2> &
  Minimum<0> &
  Maximum<1>;
  
export interface TurnoverProbability {
  readonly minimum: PercentageMultiplier;
  readonly average: PercentageMultiplier;
  readonly maximum: PercentageMultiplier;
}
```
Unfortunately, the following just returns an empty array:

```ts
// []
validate<TurnoverProbability>({
  minimum: 0.2,
  average: 0.2,
  maximum: 10,
});
```

**Comment by marcus-sa** [comment]
The issue was that I imported `TurnoverProbability` as a type only...

**Comment by marcj** [comment]
hehe yeah, the idea of TS behind `import type` was that it's always removed in compile time, no matter what. We respect that and do not embed runtime types when `import type` is used.

**Comment by marcus-sa** [comment]
> hehe yeah, the idea of TS behind `import type` was that it's always removed in compile time, no matter what. We respect that and do not embed runtime types when `import type` is used.

Is it mentioned anywhere in the documentation? I'm probably not the last to encounter this. Maybe there's a way we can improve/add error reporting?

**Comment by jacoscaz** [comment]
> hehe yeah, the idea of TS behind import type was that it's always removed in compile time, no matter what. We respect that and do not embed runtime types when import type is used.

I've just spent an embarrassing amount of time banging my head against what looked like failed validation only to finally stumble here and realise than type information is only imported if the corresponding import is not flagged as a `type` import. 

To be fair, this is clearly pointed out at the bottom of https://deepkit.io/en/documentation/runtime-types/external-types, which I had missed. However, I do think it would be a good idea to repeat this in https://deepkit.io/en/documentation/runtime-types/getting-started , particularly given the `verbatimModuleSyntax` TS option which is fairly widely used. 

@marcj would you accept a PR that updates the documentation accordingly?
