### ISSUE TITLE
[Bug] Wrong Route Matcher Generated when a Route Method Takes No Parameters and Has Path Parameters

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#304]
```ts
import { App } from "@deepkit/app";
import { ApplicationServer, FrameworkModule } from "@deepkit/framework";
import { http, HttpKernel, HttpRequest } from "@deepkit/http";
async function main() {
  @http.controller()
  class MyController {
    @http.GET("a/:id")
    route1() {}
    @http.GET("b/:id")
    route2(anyParam: HttpRequest) {}
  }
  const app = new App({
    imports: [new FrameworkModule()],
    controllers: [MyController],
  });
  await app.get(ApplicationServer).start();
  const kernel = app.get(HttpKernel);
  const response1 = await kernel.request(HttpRequest.GET("/a/1"));
  console.log(response1.statusCode); // 404
  const response2 = await kernel.request(HttpRequest.GET("/a/:id"));
  console.log(response2.statusCode); // 200
  const response3 = await kernel.request(HttpRequest.GET("/b/1"));
  console.log(response3.statusCode); // 200
}
main();
```
```
Start server ...
2 HTTP routes
HTTP Controller MyController
  GET /a/:id
  GET /b/:id
HTTP listening at http://0.0.0.0:8080
Server started.
undefined - GET "/a/1" 404 ""
404
undefined - GET "/a/:id" 200 ""
200
undefined - GET "/b/1" 200 ""
200
```

Bug locates at: https://github.com/deepkit/deepkit-framework/blob/293a335a98fa33165285c360b293ef82f1db5a26/packages/http/src/router.ts#L798-L801

**Comment by marcj** [comment]
I'd say it's less a bug in the router request matcher but more with now throwing an error when the route is invalid. So, defining `:id` and not consuming it in a parameter should throw an error instead.

**Comment by TheNightmareX** [comment]
you're actually right, but could we allow defining path parameters but not consuming it directly via parameters? I'm currently parsing and consuming path parameters using a provider which injects `HttpRequest`. I know this doesn't take advantage from the JIT compiler and doesn't match your expected usage of the framework, but it allows me to have higher level abstractions🥺

**Comment by marcj** [comment]
If your PR fixes that we can go with it I guess

**Comment by TheNightmareX** [comment]
fixed in https://github.com/deepkit/deepkit-framework/pull/306
