### ISSUE TITLE
Readonly-only constructor properties should be serialized

### ISSUE THREAD

**Issue by danfma** [deepkit/deepkit-framework#307]
The TypeScript language defines the default visibility modifier as public, so the `public` keyword should not be required for serialization when defining properties in the constructor.

For example:

```typescript
class Pilot {
  constructor(public readonly name: string, public readonly age: number) {}
}
```

The above class will be properly serialized, but the following not:

```typescript
class Pilot {
  constructor(readonly name: string, readonly age: number) {}
}
```

So if you play with serialization like this:

```typescript
const pilotSerialized = JSON.stringify(serialize<Pilot>(new Pilot('John', 30)));

console.log('pilotSerialized', pilotSerialized);

const pilotDeserialized = deserialize<Pilot>(JSON.parse(pilotSerialized));

console.log('pilotDeserialized', pilotDeserialized);
```

The first will result in the following:

```typescript
/* OUTPUT:
pilotSerialized {"name":"John","age":30}
pilotDeserialized Pilot { name: 'John', age: 30 }
*/
```

While the second one, this:

```typescript
/* OUTPUT:
pilotSerialized {}
pilotDeserialized Pilot { name: undefined, age: undefined }
*/
```

**Comment by marcj** [comment]
Thanks @danfma for the report! This is fixed in https://github.com/deepkit/deepkit-framework/commit/20cb35fae8fb0c102b92c62d6efe335ecc32a3c1

**Comment by danfma** [comment]
Superb!
