### ISSUE TITLE
[Feature] Font of the Documentation

### ISSUE THREAD

**Issue by pavel-voronin** [deepkit/deepkit-framework#314]
It's hard for me to read documentation as it uses serif typeface.

Please consider to change the font to one that is dyslexia friendly or provide an option to choose between few fonts.

Thanks a lot!

**Comment by pavel-voronin** [comment]
Yes, I am forced to use them. To be honest, I use them very rarely, as popular resources use handy fonts. E.g.: github, node.js, typescript, mdn, react, vue, express.js and so on

**Comment by pavel-voronin** [comment]
No, please. I feel my needs were not handled. At least I want to give this issue its time to gather support from another humans. This is not a bad idea to align documentation style with common practice, i beleive.

**Comment by marcj** [comment]
Font is changed to a sans serif one
