### ISSUE TITLE
Discriminated unions with two enums are not deserialized

### ISSUE THREAD

**Issue by danfma** [deepkit/deepkit-framework#317]
If you have an enum the deepkit won't be able to deserialize it correctly.

Reproduction:

```typescript
import { cast } from '@deepkit/type';

export enum StatEnginePowerUnit {
  Hp = 'hp',
}

export enum StatWeightUnit {
  Lbs = 'lbs',
  Kg = 'kg',
}

export type StatMeasurementUnit = StatEnginePowerUnit | StatWeightUnit;

console.log(cast<StatMeasurementUnit>(StatWeightUnit.Kg));
```

Expected behavior: it should be deserialized as 'kg'.

**Comment by marcj** [comment]
Can confirm this is a bug. The following is wrongly computed, likely an issue with the VM.

```typescript
    enum StatEnginePowerUnit {
        Hp = 'hp',
    }

    enum StatWeightUnit {
        Lbs = 'lbs',
        Kg = 'kg',
    }

    type StatMeasurementUnit = StatEnginePowerUnit | StatWeightUnit;
    const type = typeOf<StatMeasurementUnit>(); //kind=enum, wrong
```

**Comment by marcj** [comment]
@danfma thanks for reporting! Fixed in https://github.com/deepkit/deepkit-framework/commit/291c96c0ae74e2c90df611f8fa9894df5d52dd6b.

**Comment by danfma** [comment]
Hey, @marcj ! I don't want to press you but, is it possible to deploy a version with the fixed bugs?
