### ISSUE TITLE
Partial<O> doesn't work with annotations

### ISSUE THREAD

**Issue by hanayashiki** [deepkit/deepkit-framework#327]
```ts
import { MaxLength, metaAnnotation, typeOf } from "@deepkit/type";

interface User {
  name: string;
  password: string;
}

const annotations = metaAnnotation.getAnnotations(typeOf<Partial<User> & MaxLength<16>>());
console.log(annotations); // actually an empty array. Partial<User> seem not to keep the annotations at all.
```

**Comment by marcj** [comment]
There are several type decorators. Each uses its own annotation object. Only for non-core type decorators is `metaAnnotation` used. To get the annotation data of validation types like `MaxLength` use `validationAnnotation`.

```typescript
const annotations = validationAnnotation.getAnnotations(typeOf<Partial<User> & MaxLength<16>>());
console.log(annotations);
```

**Comment by hanayashiki** [comment]
Oh, it seems I'm using multiple `type CustomMeta = { __meta: [...] }`. So only one meta annotation can be used?

**Comment by marcj** [comment]
> So only one meta annotation can be used?

No, you can add as many type decorators as you want on a type.
