### ISSUE TITLE
meta annotations lost when using generics

### ISSUE THREAD

**Issue by hanayashiki** [deepkit/deepkit-framework#328]
```ts
type CustomA = { __meta?: ["CustomA"] };
type CustomB = { __meta?: ["CustomB"] };

type O = {} & CustomA;
type Decorate<T> = T & CustomB;

const decorated = typeOf<Decorate<O>>();

console.log(metaAnnotation.getAnnotations(decorated));
// [ { name: 'CustomB', options: [] } ]
//
// Get only `CustomB`, no `CustomA`
```

I think this is due to that `Decorate<O>` is not correctly resolved to `O & CustomA & CustomB` but possibly `O & CustomB`, thus losing the information of `CustomA`. This is the actual case I encountered with https://github.com/deepkit/deepkit-framework/issues/327

Thank you!

**Comment by marcj** [comment]
Good catch, thanks @hanayashiki! Fixed in https://github.com/deepkit/deepkit-framework/commit/88ce7d468ebea1df8e0060ccfeed6650f164a4b6
