### ISSUE TITLE
Get decorator applied to class and/or methods

### ISSUE THREAD

**Issue by CristianPi** [deepkit/deepkit-framework#334]
Any way to get decorators applied to classes/methods with inputs?

```typescript
@MyDecorator({
  value:"hello"
})
class Test{

}

const reflection = ReflectionClass.from<Test>();
reflection.hasDecorator(MyDecorator) === true
reflection.decorators[0].arguments === {value:"hello"}
...
```

**Comment by marcj** [comment]
No, decorators are not part of the type system. That's why we created [our own](https://docs.deepkit.io/english/runtime-types.html#runtime-type-decorators). The whole point of runtime types is to not abuse TS decorators anymore like many libraries currently do.

**Comment by CristianPi** [comment]
> No, decorators are not part of the type system. That's why we created [our own](https://docs.deepkit.io/english/runtime-types.html#runtime-type-decorators). The whole point of runtime types is to not abuse TS decorators anymore like many libraries currently do.

I get that, it's only a little bit difficult to port a large code base in one shot (nest -> deepkit)
that's why i was considering some middle ground reflecting decorators information, translating / proxy  ect.
It's not a deal breaker as the simple alternative is to monkey patch decorator function.
Thanks

**Comment by marcj** [comment]
Ah I see. I'm afraid it's not easily possible to make decorator calls available in runtime type system. A decorator can be an arbitrary function expression, so there is not even always meta-data associated with it. We could make the decorator function and its parameter available, but that would probably mean massive runtime overhead if a lot of decorators are used. Overall I don't think we are going to add support for that anytime soon.

**Comment by marcj** [comment]
What's your concrete use-case here? Maybe there is a better alternative than accessing oldschool TS decorators.

**Comment by CristianPi** [comment]
> Ah I see. I'm afraid it's not easily possible to make decorator calls available in runtime type system. A decorator can be an arbitrary function expression, so there is not even always meta-data associated with it. We could make the decorator function and its parameter available, but that would probably mean massive runtime overhead if a lot of decorators are used. Overall I don't think we are going to add support for that anytime soon.

I understand, it's not really a problem as i have a way to solve that.
I'm using the decorator of nest to differentiate between  injectable service, controller, entity ect,
so that i can automate discovery, and also in this case "translation" from one DI to another.

**Comment by marcj** [comment]
I guess Nest's decorators have a way to get the meta-data. There must be a way since they read it for their purposes already, but I don't know where or how.

**Comment by CristianPi** [comment]
> I guess Nest's decorators have a way to get the meta-data. There must be a way since they read it for their purposes already, but I don't know where or how.

Yes they usually apply metadata, the problem is to find the tag name ect, it's not really supposed to be public, i think.
But i'm replacing the decorators at runtime, so i can add all the meta i want.

Thanks for the support!
