### ISSUE TITLE
deserialize return undefined for type with kind === 29

### ISSUE THREAD

**Issue by CristianPi** [deepkit/deepkit-framework#338]
```typescript
import {deserialize, ReflectionClass, ReflectionKind} from "@deepkit/type";


export class Test1 {
  echo(...args: any[]): any {
    return args;
  }
}
const refTest = ReflectionClass.from(Test1);
const method = refTest.getMethod('echo');
const input = method.parameters[0];
input.type.kind === ReflectionKind.rest; // true
deserialize([], undefined, undefined, undefined,input.type) === undefined
```

It's kinda weird that the type is rest, shouldn't be a flag or something like that?  

ps: sorry reproducing the undefined i got a crash, because i inverted the data with the type :(
i corrected the issue

**Comment by marcj** [comment]
> It's kinda weird that the type is rest, shouldn't be a flag or something like that?

No, you just use it wrongly. You can not test against or serialize Rest as it is not a standalone type. It's a type expression inside a tuple or function parameters. So, you have to work with the tuple or function parameters instead. In case of your example, you have to convert the parameters to a tuple first. There are two ways to do that, here's an example:

```typescript
type t = (start: number, ...rest: string[]) => void;

const fn = typeOf<t>(); //or method
assertType(fn, ReflectionKind.function);

const type = typeOf<Parameters<never>>([fn]); //same as Parameters<t>
//equivalent to
//const type = parametersToTuple(fn.parameters);

expect(deserialize([2, '33', 44], undefined, undefined, undefined, type)).toEqual([2, '33', '44']);
```

**Comment by CristianPi** [comment]
@marcj 
thanks you very much!

i solved with
```typescript
parametersToTuple([method.type.parameters[0]]);
```

So i imagine that the tuple handle the logic of the rest expression ect.
I'm porting from typescript-rtti that works a bit differently.
