### ISSUE TITLE
ES2022 type compiler issues

### ISSUE THREAD

**Issue by fergusean** [deepkit/deepkit-framework#339]
I've only noticed this with `Pick` so far, but:

When `target` in `tsconfig.json` is set to `ES2020` or `ES2021`, [this code](https://github.com/deepkit/deepkit-framework/commit/1d984fec0839796126264b44e77e80b04593d748#diff-f647e316ee8bb0d2599cb8db20bdcc44742189e5137cd2e68a5a17d85b2b306fR1181-R1189) from the @deepkit/type tests builds the following:
```
const __ΩUser = ['id', 'name', 'password', 'P\'4!&4"&4#M'];
const __ΩReadUser = [() => __ΩOmit, () => __ΩUser, "password", 'n".#o!#'];
const type = (0, type_1.typeOf)([], [() => __ΩReadUser, 'n!']);
```

However, once changing the target to `ES2022`, the following is produced:
```
const __ΩUser = ['id', 'name', 'password', 'P\'4!&4"&4#M'];
const __ΩReadUser = ['!'];
const type = (0, type_1.typeOf)([], [() => __ΩReadUser, 'n!']);
```

**Comment by marcj** [comment]
Thanks for the report, fixed in https://github.com/deepkit/deepkit-framework/commit/c8b92a2b664995f3db6ba2cdf8956c0644cf358c
