### ISSUE TITLE
[Feature] Tool to generate a new project

### ISSUE THREAD

**Issue by H4ad** [deepkit/deepkit-framework#345]
The idea behind this is to be able to start a project with all the files configured for the deepkit.

Some issues that arise with the implementation approach:

- How should this cli be integrated with the `app.ts` cli, which is used to start a project?
- Should the cli just create the project and then the user use `app.ts`?

Some inspirations to use in creating the tool:

- [Laravel uses a website to create bash file for startup](https://laravel.com/docs/9.x#getting-started-on-linux)
- [Nest has its in the cli](https://docs.nestjs.com/cli/overview)
- [Adonis uses npm init command](https://docs.adonisjs.com/guides/installation#creating-a-new-project)
- [Using deepkit library like `npx deepkit new my-project`](https://www.npmjs.com/package/deepkit)

Personally, looking at the current deepkit design, the best option is to use `npm init`. After initialization, everything can be done using `app.ts`.
But, if you have plans to extend the functionality of the deepkit cli without relying on `app.ts`, then using `npx deepkit` might be better.

**Comment by marcj** [comment]
First version has been added here https://github.com/deepkit/deepkit-framework/commit/3088e829c89e09d7621eb916501877344064e8a8

**Comment by marcj** [comment]
This is released. You can try it via

```
npm init @deepkit/app my-app
```

Let me know what you think💪
