### ISSUE TITLE
[Github] Enable Releases tab on this repository

### ISSUE THREAD

**Issue by H4ad** [deepkit/deepkit-framework#347]
Today to see current releases, I need to click inside `tags` and then navigate to `releases`.

I like to see what's changed and github has the option to put the releases tab below the repository description, like:

![image](https://user-images.githubusercontent.com/12551007/182992529-32245753-e365-4929-8ac8-3036c17f027c.png)

This is just an option you can change here:

![image](https://user-images.githubusercontent.com/12551007/182992573-11b18176-2c00-43aa-b83e-f77c8f01e6da.png)

Then:

![image](https://user-images.githubusercontent.com/12551007/182992598-0bfaf889-029b-4a14-a41c-9d95bdcf66f0.png)

**Comment by marcj** [comment]
Good idea, I was already wondering why it doesn't show up like in my other repositories. I never manually enabled it though.

Thanks, done
