### ISSUE TITLE
Middlewares are not applied when specifying multiple matching routes

### ISSUE THREAD

**Issue by NexZhu** [deepkit/deepkit-framework#348]
Middlewares are not applied when specifying multiple matching routes:

This won't work:
```ts
  middlewares: [
    httpMiddleware.for(SomeMiddleware).forRoutes({
      path: '/pathA',
    },
    {
      path: 'pathB',
    }),
  ]
```

While this works:
```ts
  middlewares: [
    httpMiddleware.for(SomeMiddleware).forRoutes({
      path: '/pathA',
    }),
    httpMiddleware.for(SomeMiddleware).forRoutes({
      path: 'pathB',
    }),
  ]
```

Haven't found the related code yet but I guess it's similar cause to this issue (`and` logic is used instead of `or` logic in matching)
https://github.com/deepkit/deepkit-framework/issues/284

**Comment by marcj** [comment]
Thanks for the report, fixed in https://github.com/deepkit/deepkit-framework/commit/b139e70b91b5b865e37de55c193e8ff9e0e60cfc
