### ISSUE TITLE
ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by icaro-capobianco** [deepkit/deepkit-framework#365]
```
Error [ERR_MODULE_NOT_FOUND]:
Cannot find module 
'path-to-workspace\node_modules\.pnpm\@deepkit+orm@1.0.1-alpha.75_vmoesvlf2vrqpaad5ssdfunk6m\node_modules\@deepkit\orm\dist\esm\src\database'
imported from
path-to-workspace\node_modules\.pnpm\@deepkit+orm@1.0.1-alpha.75_vmoesvlf2vrqpaad5ssdfunk6m\node_modules\@deepkit\orm\dist\esm\index.js
```
Yes the file paths are correct and they do exist. No other dependency causes this error.
I am using PNPM
Using node v16.11.0
<details>
  <summary></summary>
   Another wonderful day in JS land
</details>

**Comment by marcj** [comment]
we do not have explicit file extension in imports yet, so ESM in Node does not work (there is no such file `\dist\esm\src\database`). Either use the option to support that (--experimental-specifier-resolution=node) or don't use ESM.
