### ISSUE TITLE
[BUG] - Problem with Email validation on a controller router

### ISSUE THREAD

**Issue by JohnnyJumper** [deepkit/deepkit-framework#367]
Sometimes the deepkit validation fails when it shouldn't.

<img width="1728" alt="Screen Shot 2022-08-26 at 2 53 12 PM" src="https://user-images.githubusercontent.com/16522024/186995687-c8aedf04-853a-4e8c-9979-c46651b50422.png">

On the screenshot you can clearly see that one of the two requests I made didn't pass the validation. The same exactly input and two different outputs. 

Steps to reproduce:

1. git clone https://github.com/JohnnyJumper/deepkit-but-report /tmp
2. cd /tmp/deepkit-but-report
3. yarn install
4. yarn dev

open the _debug console

And spam the single endpoint with valid email.

Some requested are passed with validation and others throw an error. This is very scary and I need it to be fixed in order to utilize deepkit framework in production.. Can someone help me out?

**Comment by Spshulem** [comment]
^ Would love to see something be done about this; pretty scary bug - blocking use

**Comment by JohnnyJumper** [comment]
The problem was not related with deepkit. the issue was in incorrect regex flag '/g' 
https://stackoverflow.com/questions/19448957/why-is-regexp-test-not-consistent

Closing this issue
