### ISSUE TITLE
install-compiler must be run before bootstrap

### ISSUE THREAD

**Issue by trollkotze** [deepkit/deepkit-framework#368]
Following the instructions in [DEVELOPMENT.md](https://github.com/deepkit/deepkit-framework/blob/master/DEVELOPMENT.md):

```git clone https://github.com/deepkit/deepkit-framework.git
cd deepkit-framework
npm install
npm run bootstrap
npm run link
npm run install-compiler
```

The step `npm run bootstrap` fails with this error:

```Error: Cannot find module '/home/trollkotze/deepkit-framework/packages/type-compiler/dist/cjs/install-transformer.js'```

Apparently `npm run install-compiler` needs to be run first.
This should be updated in the `DEVELOPMENT.md` file.

**Comment by marcj** [comment]
It doesn't fail, it just prints an error. The `bootstrap` command continues to work as expected.

**Comment by marcj** [comment]
To omit printing the error we just need to adjust https://github.com/deepkit/deepkit-framework/blob/master/packages/type-compiler/package.json#L24
