### ISSUE TITLE
[question] basic setup

### ISSUE THREAD

**Issue by franjom** [deepkit/deepkit-framework#370]
Hi.

I've been playing around with deepkit, following [documentation](https://docs.deepkit.io/english/runtime-types.html) to get it up and running.

As far as I can tell, this _should_ work, based on these test cases [here](https://github.com/deepkit/deepkit-framework/blob/e0ff6b57d0aeeddf52152cc51adf64e3f0e5e0e1/packages/type/tests/receive-type.spec.ts)

![image](https://user-images.githubusercontent.com/43521521/189192887-583aae4d-824d-4b67-9e5e-95b082e31ba1.png)

however, when i spin this up I get this error:
![image](https://user-images.githubusercontent.com/43521521/189192968-9c646d15-d077-4d59-92e4-0eac90eaaf26.png)

this is my tsconfig:
![image](https://user-images.githubusercontent.com/43521521/189193017-89de2770-2630-4abc-bbe5-d943e7f9c5b9.png)

and my webpack config
![image](https://user-images.githubusercontent.com/43521521/189193090-ff35c40f-2ce9-4aeb-8a6c-a1dadc903fd2.png)

I' ve been literally following documentation and just trying to get it up and running so I can play around but with no luck.
Am I doing something wrong? Do I have completely wrong expectations?

Any help would be appreciated

**Comment by marcj** [comment]
Could be many reasons, screenshots don't tell enough to make a guess, so I'd advise to post actual code in a git repository that acts as full reproduction case

**Comment by franjom** [comment]
it seems that webpack dev server was causing this issue...
I fixed it and it works as expcted, so closing.
