### ISSUE TITLE
Documentation: please provide working examples

### ISSUE THREAD

**Issue by mindplay-dk** [deepkit/deepkit-framework#391]
Hi,

Twice now, I've attempted to test drive this framework, and gotten nowhere.

The [framework](https://docs.deepkit.io/english/framework.html) [runtime](https://docs.deepkit.io/english/runtime-types.html#runtime-types-installation) installation instructions are all incomplete - they don't even specify which packages should be installed.

Making qualified guesses (based on the `import` statements) the farthest I've gotten is to obscure compiler errors like this:

```
/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:99626
                throw e;
                ^

Error: Debug Failure. Unexpected node.
Node 294 was unexpected.
    at classElementVisitorWorker (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79177:37)
    at /home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79156:92
    at saveStateAndInvoke (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79064:27)
    at /home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79156:45
    at visitArrayWorker (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:77063:48)
    at Object.visitNodes (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:77032:23)
    at visitClassDeclaration (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79363:216)
    at visitTypeScript (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79265:28)
    at visitorWorker (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79100:24)
    at sourceElementVisitorWorker (/home/mindplay/workspace/try-deepkit/node_modules/typescript/lib/tsc.js:79115:28)
```

Please, can provide either:

1. Working documentation (from zero to deepkit)
2. A working example (repository)
3. A boilerplate tool to generate an empty project

These are the typical options - and honestly, my preference would be the un-fancy option, to just have working documentation. I've seen a few too many projects based on copy/pasting or generating boilerplates, which tend to have a bunch of features the author doesn't even know how to use. (I know that's not in tune with JS ecosystem trends, but I'm very much in favor of learning and understanding every line of code I check in.)

Ideally, I'd like to see working documentation for two setups:

1. Vanilla `tsc` (with whatever is required to watch and restart on change.)
2. `ts-node` (or `tsx`, if possible - I've had many problems with `ts-node`, and I'm not alone in that boat.)

I know your recommended approach is to use `ts-node` - if it's possible to create a setup with `ts-node` (or `tsx`) for development and `tsc` for production builds, that might be the ideal scenario.

Be sure to list your prerequisites as well, please. It looks like your framework needs Python or `node-gyp` for certain things? Some of your packages I haven't been able to install because of failing installation scripts. Since package managers don't seem to account for `node` and `npm` versions or other install-time dependencies, describing the system and environment requirements is quite important.

It looks like you have a very interesting thing here, but can you please try to make it more accessible?

Thanks. 🙂

**Comment by marcj** [comment]
Yes, I'll try. Can you please elaborate what you mean with: 
> The [framework](https://docs.deepkit.io/english/framework.html) [runtime](https://docs.deepkit.io/english/runtime-types.html#runtime-types-installation) installation instructions are all incomplete - they don't even specify which packages should be installed.

Do you mean typescript dependencies?

> Making qualified guesses (based on the import statements) the farthest I've gotten is to obscure compiler errors like this:

That's a very weird error. My guess is that a incompatible TS version is used.

> Working documentation (from zero to deepkit)
> A working example (repository)
> A boilerplate tool to generate an empty project

I think a getting started guide would help here a lot. Working repo is also a good idea. We have here and there a few Github repo examples (like deepkit bookstore), but they are nowhere linked yet).
A boilerplate tool (`npm init @deepkit/app` is already in master and will be released soon.

**Comment by mindplay-dk** [comment]
> Do you mean typescript dependencies?

I meant NPM packages - both regular and dev dependencies.

> My guess is that a incompatible TS version is used.

Yes, that seems likely - this is another reason why you need to specify which packages (and versions) to install.

I understand the installation order could affect things as well? Something else a tutorial needs to cover.

> If you can provide a repo to reproduce that would be great.

I will push this to a public repo later and let you know. (on a different computer right now...)

Thanks. 🙂

**Comment by marcj** [comment]
`@deepkit/app` has been released and its now possible to get a Deepkit app simply via 

```
npm init @deepkit/app my-deepkit-app
````

after it installed everything, you can start it and play around with it:

```
cd my-deepkit-app
npm run app server:start
```

Open http://localhost:8080/_debug/ or http://localhost:8080/name/world

**Comment by marcj** [comment]
I assume this has been resolved, so I close this one. Feel free to point out what is still missing for you
