### ISSUE TITLE
@deepkit/type does not validate Date type 

### ISSUE THREAD

**Issue by chuyik** [deepkit/deepkit-framework#412]
## issue
The `Date` type is not working as expected:

```ts
import { validate } from "@deepkit/type";

class Account {
  public name: string;

  // declare a Date type
  public createdAt: Date;
}

console.log(
  "validate result: ",
  validate<Account>({
    name: "jack",
	// no matter what the value of `createdAt` is, it does not raise error
    createdAt: 123,
  })
);

```

## screenshot
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6262943/219553870-b6539688-1eb8-43b9-8e27-2d9c0722bb97.png">

## playground
https://codesandbox.io/p/sandbox/gracious-scooby-p7xh4z?file=%2Fsrc%2Findex.ts&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A12%7D%5D

## versions
"typescript": "4.9.5"
"@deepkit/core": "1.0.1-alpha.77"
"@deepkit/type": "1.0.1-alpha.85"
"@deepkit/type-compiler": "1.0.1-alpha.83"

**Comment by marcj** [comment]
Good catch, thank you! Fixed in https://github.com/deepkit/deepkit-framework/commit/10868e4ffda18d645a61331109c06fb99bda2c01
