### ISSUE TITLE
[ question ] compatibility in projects built by vite

### ISSUE THREAD

**Issue by ZHan-F** [deepkit/deepkit-framework#413]
Hi
I follow the docs and try to use @deepkit/type in my vue3 project built by vite , it doesn't work even replicating the scenario in the docs .
Error screenshot ：
![error](https://user-images.githubusercontent.com/53553340/219852621-665d6980-10e6-4cd0-95cb-54355a65cfc1.jpg)

But in project built with vue-cli , it works correctly.

So I want to ask , it cannot work with vite or the docs has something not mentioned ?
hope to get your reply

**Comment by marcj** [comment]
Vite uses esbuild (alternative TypeScript compiler), right? If so, then Deepkit is not supported. Deepkit requires the official TypeScript compiler (tsc), so if you can get Vite to work with tsc, then Deepkit will work fine.

**Comment by ZHan-F** [comment]
Thank you for your reply

**Comment by marcj** [comment]
Vite is now supported via `@deepkit/vite`,

```typescript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import { deepkitType } from "@deepkit/vite";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react(), deepkitType()],
})
```

see example repository here: https://github.com/marcj/typescript-react-dependency-injection
