### ISSUE TITLE
[ORM] allow to exclude properties from SQL generation

### ISSUE THREAD

**Issue by marcj** [deepkit/deepkit-framework#435]
like 

```typescript
interface MyState {};

class MyEntity {
    id: number & PrimaryKey = 0;
    title: string = '';

    //volatile state
    private state: MyState & ExcludeDatabase;
}
```

The type `ExcludeDatabase` (or maybe a better name) would be new. Fields with this type won't be part of migration or any sql (SELECT, UPDATE, INSERT) generation. They would be part of regular serialisation though (which could be disabled via regular `Excluded` type).

**Comment by CristianPi** [comment]
**Transient** would be nice.

**Comment by marcj** [comment]
Is implemented via
