### ISSUE TITLE
Marshal.ts JIT crash on validation of keys with `:`, `-` or `#`

### ISSUE THREAD

**Issue by hilkeheremans** [deepkit/deepkit-framework#44]
Minimal repro
```
// index.ts
import 'reflect-metadata';
import { validate, f } from '@marcj/marshal';

class Test {
  constructor() {}
  @f public 'some:prop'?: string;
}

const data = {
  'some:prop': 'hello',
};

const validated = validate(Test, data);
```
will result in
```
jit code
        return function(_data, _path, _errors) {
            _path = _path ? _path + '.' : '';
            _errors = _errors || [];

        var value = _data.some:prop;
        if (undefined !== value && null !== value) {

            //property some:prop, string
            if ('string' !== typeof value) _errors.push(new ValidationError(_path + 'some:prop', "invalid_string", "No string given"));


        } else {
            _errors.push(new ValidationError(_path + 'some:prop', 'required', 'Required value is undefined or null'));
        }

            return _errors;
        }


/Users/hilkeheremans/projects/thinman/repro/node_modules/@marcj/marshal/src/jit-validation.ts:218
        const compiled = new Function(...context.keys(), functionCode);
                                                         ^
SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Object.jitValidate (/Users/hilkeheremans/projects/thinman/repro/node_modules/@marcj/marshal/src/jit-validation.ts:218:58)
    at Object.validate (/Users/hilkeheremans/projects/thinman/repro/node_modules/@marcj/marshal/src/validation.ts:97:12)
    at Object.<anonymous> (/Users/hilkeheremans/projects/thinman/repro/src/index.ts:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (/usr/local/Cellar/nvm/0.34.0/versions/node/v12.9.1/lib/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/Cellar/nvm/0.34.0/versions/node/v12.9.1/lib/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```
`var value = _data.some:prop;` is probably to blame here, aka https://github.com/marcj/marshal.ts/blob/master/packages/core/src/jit-validation.ts#L192 ?

**Comment by marcj** [comment]
Yes, that use-case was never in mind. I think that serialization is broken as well for those kind of property names.

**Comment by hilkeheremans** [comment]
If you want, I can see if I can submit a PR to provide a fix -- it should be as simple as switching to bracket notation, which (at least on V8) should have no appreciable performance impact.

**Comment by marcj** [comment]
Yes, sure go ahead :) We'd need to adjust multiple places:
- packages/core/src/jit.ts:303,304,306
- packages/core/src/jit.ts:328,329,330,331
- packages/core/src/jit.ts:416
- packages/core/src/jit.ts:419
- packages/core/src/jit.ts:420
- packages/mongo/src/compiler-templates.ts:135
- packages/core/src/jit.ts:392,399,401 `var c_` => `var c['`
- packages/core/src/jit-validation.ts:196
- packages/core/src/jit-validation.ts:201

**Comment by hilkeheremans** [comment]
Just to let you know I am still on this, I hope to be submitting a PR sometime next week.

**Comment by hilkeheremans** [comment]
OK, so this got lost for a few months. Sorry about that. Is this still relevant with the transition to `@deepkit/type`?

**Comment by marcj** [comment]
Mh, the thing is, quite some code (json serializer, bson serializer, validator, ORM, SQL builder, SQL schema migrator, and probably more), depends on the fact that property names do not contain special characters outside of `a-zA-Z0-9_`, so supporting for example `:` in a property name is _quite_ a challenge. It should be possible to support it for json serialization and validation though.

**Comment by hilkeheremans** [comment]
Alright. For me it's not that big of an issue. I'll close this issue so you can scratch this off your list of minor concerns. :-)

Thanks and looking forward to the release of deepkit!
