### ISSUE TITLE
File upload restrictions

### ISSUE THREAD

**Issue by fergusean** [deepkit/deepkit-framework#442]
Would be nice to be able to set custom options for `formidible` to set max file size, filter, etc.  Not a huge deal for me since the max body size can be controlled by the upstream proxy, but for those not using a reverse proxy, could allow a bad actor to fill their disk.

**Comment by marcj** [comment]
Implemented in https://github.com/deepkit/deepkit-framework/commit/f6fb8cc90be9729c2f9bf834aba4331887cb7ba5
