### ISSUE TITLE
Debugger stops at wrong line

### ISSUE THREAD

**Issue by ZPiDER666** [deepkit/deepkit-framework#445]
in a class i set a breakpoint, then i start the server and the breakpoint "jumps" a few lines up. when the breakpoint hits, it has the originally intended context, but visually shows at the wrong line. effectively this prevents me from using the debugger.

i suspect, that the transformer makes a change before the sourcemap is being built and therefore the lines are off. whats weird is that the lines always seem to be offset "upwards" and i would rather expect the transformers to insert code (and therefore push the actual lines "downwards".

- VSCode
- node 19.5
- typescript 4.9.4
- ts-node 10.9.1
- i do NOT use the patched TSNode that comes with deepkit, instead i use ttypescript (1.5.15) with a standard ts-node because i need my own transformers also.
-- because of this i have a wrapper for the deepkit transformer

**Comment by marcj** [comment]
Can you upload/provide the source/minimql reproduction code? Or a built folder where we have the js, .map, and .ts files. then we can use sourcemap-viewers to see exactly how the source was mapped. this way we can see if the mapping is correct or needs adjustments

**Comment by ZPiDER666** [comment]
yes, i will build a minimal project!

**Comment by ZPiDER666** [comment]
i finally managed to get the mini test project running, sorry4delay, npm gave me troubles

set a breakpoint in DataAPI, for example line 11, then start dev with debug (i use the NPM SCRIPTS view > dev > debug icon).

[deepkit-test-debugger-problem-min.zip](https://github.com/deepkit/deepkit-framework/files/11312510/deepkit-test-debugger-problem-min.zip)

**Comment by marcj** [comment]
You have in your tsconfig.json ttypescript configured to use typescript's transformer:

```

		"plugins": [
			{ "transform": "./src/transformers/transformer.ts" },
			{ "transform": "./src/transformers/deepkit-tf.ts" }
		],
```


this is not necessary, since deepkit automatically patches `node_modules/typescript`. In your case the transformer ran twice which broke some stuff. Removing that plugins line `deepkit-tf.ts` fixes it
