### ISSUE TITLE
Is it possible to use DeepKit without the runtime?

### ISSUE THREAD

**Issue by matthew-dean** [deepkit/deepkit-framework#447]
Deepkit has a lot of really, really useful type constraints, such as defining a string as needing to be within a certain pattern. Is it possible to use `@deepkit/type` to define types in an NPM library, such that it will give feedback / errors about incorrect types when used in VSCode or with TSC? In other words, I don't want to use runtime validation, just code-time validation.

**Comment by marcj** [comment]
Currently, on all our validation types there are no TypeScript constraints attached. That means you can assign any value to a type annotated with Deepkit decorator types and have to call e.g. validate() to make sure it's actually that type. Unfortunately, TypeScript is not powerful/fast enough to make it possible with all our available validation/constraints types.
