### ISSUE TITLE
[type] [Suggestion] TS "satisfies" keyword for autowrapping JSON.parse

### ISSUE THREAD

**Issue by svr93** [deepkit/deepkit-framework#451]
TypeScript provides `satisfies` keyword to ensure that type meets some requirements, e.g.:

```typescript
type User {
  name: string
}

const user = { name: "John" } satisfies User
```

Instead of explicit `deserialize` call, some logic can be used when JSON.parse was called:

```typescript
const user = JSON.parse('{"name": "Alex"}') satisfies User

// the same thing >>>:

const user = deserialize<User>(JSON.parse('{"name": "Alex"}'))
```

By using `satisfies` this way no extra imports are needed - everyone can use "usual TypeScript" where possible.

**Comment by marcj** [comment]
That's not how deserialization works. This is an example where deserialization actually happens:

```typescript
type User = {name: number}

const user = deserialize<User>({ name: "2" });
```

or: 

```typescript
type User = {date: Date}

const user = deserialize<User>({ date: "2023-05-21T17:25:29.510Z" });
```

in these use cases satisfies would actually error:

```typescript
type User = {date: Date}

const user = { date: "2023-05-21T17:25:29.510Z" } satisfies User;
```

So, making satisifies do that would mean to alter the way this expression is type checked, which is a big no no for this project.
