### ISSUE TITLE
Types derived from array values are not correctly inferred

### ISSUE THREAD

**Issue by jonohill** [deepkit/deepkit-framework#452]
Deepkit does not currently understand a union type derived from a const array. The result of this is that the validatedDeserialize function resets a valid value to the first possible value in the union.

Example:
```
import assert from 'assert';

import { typeOf, validatedDeserialize } from '@deepkit/type';


const VALUES = [
    'this',
    'that',
    'another'
] as const;

// derived: type Value = "this" | "that" | "another"
type Value = typeof VALUES[number];

interface Item {
    value: Value;
}

const item = {
    value: 'another'
};

const validatedItem = validatedDeserialize<Item>(item);

const type = typeOf<Value>();
console.log(type);

assert.strictEqual(validatedItem.value, 'another');
```

```
❯ npx tsc && node index.js
{
  kind: 13,
  typeName: 'Value',
  literal: 'this',
  typeArguments: undefined
}
node:assert:125
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'this'
- 'another'
```

I can see in the compiled code that the const array is referenced, but this is the limit of what I've looked in to.
```
const __ΩValue = [() => VALUES, 'i!\'f'];
```

**Comment by marcj** [comment]
type inference from expressions like `typeof VALUES[number];` is not supported. we do not have any runtime information about the types of variables and do not want to add that overhead since it would be a too big performance hit

**Comment by jonohill** [comment]
I don't think runtime type inference is required, in that a typeof const is known at build time. The typescript compiler can see and enforce the possible values at build time.

However I'm not familiar with Deepkit's internals so I'll note this limitation.

**Comment by marcj** [comment]
We do not use the TypeChecker instance which knows this stuff, but only the transformer API. Hence we have no symbolic knowledge about computed types. This is one of the tradeoffs, we can't support all without making compilation super slow + increase runtime overhead too much
