### ISSUE TITLE
[Bug:Type] export '__ΩXXX' (imported as '__ΩXXX') was not found in './types' (possible exports: XXX)

### ISSUE THREAD

**Issue by MunMunMiao** [deepkit/deepkit-framework#453]
example: https://github.com/MunMunMiao/deepkit-bug-replay

repro steps:

1. pnpm i
2. pnpm run watch:lib
3. pnpm run start
4. go to `projects/lib/src/lib/lib.component.ts`. change template

now you can see 
`./src/app/app.component.ts:40:9-25 - Error: export '__ΩTestInterface' (imported as '__ΩTestInterface') was not found in './types' (possible exports: TestClass)`

**Comment by alexkreidler** [comment]
I have a similar error. After running `pnpm i @deepkit/app @deepkit/framework @deepkit/http deepkit-openapi`, with this code:
```ts
import { OpenAPIModule } from "deepkit-openapi";
import { App } from "@deepkit/app";
import { FrameworkModule } from "@deepkit/framework";
import { http } from "@deepkit/http";

class MyPage {
  @http.GET("/")
  helloWorld() {
    return "Hello World!";
  }
}

new App({
  controllers: [MyPage],
  imports: [
    new OpenAPIModule({ prefix: "/openapi/" }),
    new FrameworkModule({ httpLog: true })
  ]
}).run();
```
I get:
```
file:///home/alex/c2/toky/backend/node_modules/.pnpm/@deepkit+broker@1.0.1-alpha.97_@deepkit+bson@1.0.1-alpha.97_@deepkit+core-rxjs@1.0.1-alpha.97_4gm36sj6b3fhdelbvagfaxbesu/node_modules/@deepkit/broker/dist/esm/src/client.js:14
import { __ΩBSONDeserializer as __ΩBSONDeserializer } from '@deepkit/bson';
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@deepkit/bson' does not provide an export named '__ΩBSONDeserializer'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by marcus-sa** [comment]
I'm getting the same error as @alexkreidler when trying to run a Deepkit app using https://bun.sh

**Comment by MunMunMiao** [comment]
@marcj This problem has not been solved yet. Please refer to me as a reproduction case

**Comment by timvandam** [comment]
Does angular use `tsc` or something else? I sometimes have similar errors when using `tsc` in watch mode

**Comment by MunMunMiao** [comment]
> Does angular use `tsc` or something else? I sometimes have similar errors when using `tsc` in watch mode
use angular.

you can use see my repro
