### ISSUE TITLE
Extending an omitted interface doesn't work

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#464]
```ts
import { ReflectionClass, typeOf, validate } from '@deepkit/type';

test('validate omitted extended interfaces', () => {
  interface A {
    readonly a: string;
    readonly value: string;
  }

  interface B extends Omit<A, 'value'> {
    readonly b: string;
  }

  const type = typeOf<B>();
  console.log(validate({ b: '' }, type)); // []
  console.log(ReflectionClass.from(type).getPropertyNames()); // [ 'b' ]
});
```

**Comment by marcus-sa** [comment]
Interesting, `Omit` doesn't work at all.
```ts
import { typeOf, validate } from '@deepkit/type';

test('validate nested interfaces', () => {
  interface A {
    readonly a: string;
    readonly value: string;
  };

  type B = Omit<A, 'value'>;

  const type = typeOf<B>();
  console.log(validate({}, type)); // []
});
```

**Comment by marcus-sa** [comment]
Pick only works for inline types as well.

**Comment by marcj** [comment]
weird, works for me. Added also a test that shows Omit works with non-inline types: https://github.com/deepkit/deepkit-framework/commit/a47111c53f43ceb11cbbf4f4fb72c8d72eac9507

**Comment by marcus-sa** [comment]
> > weird, works for me. Added also a test that shows Omit works with non-inline types: [a47111c](https://github.com/deepkit/deepkit-framework/commit/a47111c53f43ceb11cbbf4f4fb72c8d72eac9507)
> 
> I assume it's because my typescript target was set to `esnext`.

@marcj yeah it works fine when it's set to `es2022`.
`@typescript/vfs` is bugged and doesn't return the correct lib files for `esnext`.
