### ISSUE TITLE
[type] Feature: reflect type definitions imported via `import type`

### ISSUE THREAD

**Issue by gwhitney** [deepkit/deepkit-framework#466]
Suppose that the file remote.ts contains:
```
export interface ImportedInterface {
   item: (a: number) => string
}
```
while in the same directory local.ts contains:
```
import type {ImportedInterface} from './remote.js'

interface LocalInterface {
   item: (a: number) => string
}

import {stringifyType, typeOf} from '@deepkit/type'

console.log('Locally:', stringifyType(typeOf<LocalInterface['item']>()))
console.log('Remotely:', stringifyType(typeOf<ImportedInterface['item']>()))
```

Then compiling the whole directory and executing local.ts produces:
```
Locally: item(a: number): string
Remotely: any
```

On the other hand, if one removes the word `type` in the first line of local.ts so that it simply does
```
import  {ImportedInterface} from './remote.js'
```
then compiling and running produces the more desirable output
```
Locally: item(a: number): string
Remotely: item(a: number): string
```

Is there something else I need to do to make the reflection work when I just `import type`?

Or if reflection of  types imported via  `import type` isn't currently supported, is there any chance that it could be implemented? Thanks!

**Comment by gwhitney** [comment]
Oh, sorry, the setup I am doing this in for reference:
```
> pnpm ls
dependencies:
@deepkit/type 1.0.1-alpha.97

devDependencies:
@deepkit/type-compiler 1.0.1-alpha.97
@types/node 20.5.0
typescript 5.1.6
```

**Comment by gwhitney** [comment]
Exactly, I need the type information at runtime, but it happens to be coming in from an `import type`. Are you saying that there's a practical obstruction to reflecting type information that the Typescript compiler is obtaining via `import type`? Or that philosophically I shouldn't need/want to use information about such types at runtime?

**Comment by marcus-sa** [comment]
@gwhitney I'm saying you cannot use `import type` at all...

**Comment by marcj** [comment]
TypeScript itself specified `import type {ImportedInterface} from` with "do not at all cost emit runtime/JS code", which we follow. If you want to import  types + runtime information, use regular `import` without `type`, e.g. `import {ImportedInterface} from`

**Comment by gwhitney** [comment]
Well but there are cases with recursive types in which import type works but import does not. What does someone who wants runtime type information on such types do? Seems like the opt-in/out mechanism for generating runtime type information should be distinct from import/import type, imo.

**Comment by marcj** [comment]
Recursive types are supported at runtime to a certain extend. If it breaks, your other runtime code likely breaks as well, so you must break/solve the circular dependency.
