### ISSUE TITLE
websockets rpc not working in ESM project

### ISSUE THREAD

**Issue by uplight-dev** [deepkit/deepkit-framework#470]
I'm trying to introduce the deepkit/rpc in a very simple project.

My package.json has "type": "module" and the tsconfig.json:
```

    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
```

To run the code I just do tsc followed by node dist/server.js.

server.js has the example code from your documentation:

```
import { rpc, RpcKernel } from '@deepkit/rpc';
import { RpcWebSocketServer } from '@deepkit/rpc-tcp';
import {WebSocketServer} from 'ws';

@rpc.controller('myController')
export class Controller {
    @rpc.action()
    hello(title: string): string {
        return 'Hello ' + title;
    }
}

const kernel = new RpcKernel();
kernel.registerController(Controller);
const server = new RpcWebSocketServer(kernel, 'localhost:8081');
server.start({});
```

But I get this error:

`TypeError: ws.Server is not a constructor`

Could you please help?

Thanks

**Comment by uplight-dev** [comment]
Also trying without WebSockets is unclear.

Could you please provide an example using RpcTcpClientAdapter as well?

**Comment by marcj** [comment]
I added an example https://github.com/deepkit/deepkit-framework/tree/master/examples/rpc-websockets

**Comment by uplight-dev** [comment]
Actually from your example I see you're still using commonjs. 

Could you please update your package.json to include "type":"module" and these options in tsconfig?

```
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
```

In meantime I managed to get RpcTcpClientAdapter to work by looking at a legacy deepkit documentation and it works also within an ESM enviroment (not commonjs).
But it'd be nice to have it working with WebSockets.

**Comment by uplight-dev** [comment]
any feedback on this?

**Comment by marcj** [comment]
Yes, fixed an issue in rpc-tcp package which should support now ESM. will be available next release

**Comment by marcj** [comment]
See https://github.com/deepkit/deepkit-framework/commit/727afc440d65a44fd8637bebfdb877131b4be51e

**Comment by uplight-dev** [comment]
perfect will look into it, thanks a lot!

**Comment by marcj** [comment]
This is now fixed and released
