### ISSUE TITLE
Update Nest Package Version

### ISSUE THREAD

**Issue by jmcdo29** [deepkit/deepkit-framework#48]
I'm pretty sure I you mention that you no longer use Nest, but I was wondering if we could get a `peerDep` change on the nest specific package to use `>5.0.0` instead of `^5.0.0`. I've been using it myself and have had very few problems on v7, other than the install warnings about peer dependency version mismatch. It's something ignorable, just wondering if we could get the update.

**Comment by marcj** [comment]
Sure, do you want to create a PR for it?

**Comment by jmcdo29** [comment]
No problem! I'll try to create one tonight

**Comment by marcj** [comment]
I dropped Nest support entirely since we provide now an own application framework that is overall much faster. Going to close this one as there is no action to do.
