### ISSUE TITLE
rpc on classes returned by controllers

### ISSUE THREAD

**Issue by uplight-dev** [deepkit/deepkit-framework#482]
Hi

Is it possible to expose just an interface to a Client and call methods in classes returned by Controllers that are executed back on the Server that returns them?

For below code, in order to call Resolver.resolve, I need that the implementation of Resolver is shared by Client and Server. 
Can it exist only on Server, and have resolve be called remotely, as a callback, by Client?

```
@rpc.controller('controller')
export class Controller implements IController {
    @rpc.action()
    createResolver() : IResolver {
        return new Resolver();
    }
}

@entity.name('resolver')
export class Resolver implements IResolver {
    private cfg: Json;

    @rpc.action()
    init(cfg: Json) : void {
        this.cfg = cfg;
    }

    @rpc.action()
    resolve() {
        console.log(JSON.stringify(this.cfg));
    }
}

const kernel = new RpcKernel();
kernel.registerController(Controller);
const server = new RpcTcpServer(kernel, 'localhost:8081');
await server.start();

```

**Comment by marcj** [comment]
No, it's not possible like that. But since `Controller` is instantiated for each client, you can create that Resolver as class property and access it like that


```typescript
export class Controller {
    resolver = new Resolver;

    @rpc.action()
    resolve() : any {
        return this.resolver.cfg;
    }
}

````

**Comment by marcj** [comment]
Actually, you can, but you have to remove `rpc.action` at all the methods of `Resolver`, since resolver code runs on the client, not on the server.
