### ISSUE TITLE
MongoDb orm doesn't yet support batches and large result over 16 MB are cut off

### ISSUE THREAD

**Issue by colorcube** [deepkit/deepkit-framework#486]
There's a todo in `packages/mongo/src/client/command/find.ts`:

`//todo: implement fetchMore and decrease batchSize`

No matter how big the batchSize size is, the mongodb server has a limit of 16 MB for one batch. If your query result is greater than that (as bson), you won't get the full result because deepkit doesn't fetch the next result batch.

There won't be an error which is confusing because the result is not what you expect, while count() gives you the right number.

**Comment by marcj** [comment]
It was implemented at one point, we just have to go through the history. We need it also for aggregate command
