### ISSUE TITLE
Error: No type given

### ISSUE THREAD

**Issue by colemars** [deepkit/deepkit-framework#489]
Hello, I copy and pasted your doc example into a new project and am receiving the above error, `Error: No type given`.

```ts
import { valuesOf } from "@deepkit/type";

type Groups = "admin" | "user" | "guest";

const groups = valuesOf<Groups>(); // ['admin', 'user', 'guest']

console.log("groups", groups);
```

And [the project](https://github.com/colemars/test-deepkit/blob/main/src/index.ts)

Any guidance would be great as I really would like to make use of this library

**Comment by timvandam** [comment]
You shouldn’t pass an array here as (iirc) it will be used as type instead of using the generic type

where in the docs is this example?

**Comment by colemars** [comment]
Sorry, that was leftover from debugging. The result is the same with or without the array there

**Comment by colemars** [comment]
I'll happily just accept a repo in which the above example from the docs is working

**Comment by timvandam** [comment]
The issue is probably that you do not have reflection enabled in your TSConfig. It should be a top level property, ie
```json
{
    "compilerOptions": { ... },
    "reflection": true
}
```

**Comment by colemars** [comment]
Dang, got that example working but none of the `ReflectionClass` examples will work now.. bummer! Will check back in in a few months maybe.

**Comment by timvandam** [comment]
It wirks for me 🤷‍♂️ It only works on classes compiled with the deepkit type compiler installed. So if you’re trying to use third party classes it won’t work
