### ISSUE TITLE
Suggestion: Add more common validation decorators to library

### ISSUE THREAD

**Issue by chuyik** [deepkit/deepkit-framework#50]
Hi @marcj, thanks for this interesting library, after comparing to `class-validator`, I think this one is definitely easier to use, with shorten validator, class field reference recognition and default value.

But I also find that this library does not provide built-in common validation decorators like `IsEmpty` / `Min` / `Max` / `Matches` like [`class-validator` provides](https://github.com/typestack/class-validator#validation-decorators).

Of course marshal.ts allow us to implement custom validators, but it's better if it could provide those common validation decorators like class-validator has.

**Comment by marcj** [comment]
Yeah, absolutely. We could theoretically just create all validators available in class-validator to have the same feature-set, but I'm not yet sure how the API should look like. What comes into my mind are those API options:


1. Put all methods to the `@f` decorator.

```typescript
import {f} from 'marshal';

class User {
     @f.notInTheFuture() birthdate: Date;

     @f.email() email: string;

     @f.positive() logins: number;
}
```

2. Put all methods encapsulated


```typescript
import {f, validator} from 'marshal';

class User {
     @f.validator(validator.NoInTheFuture) birthdate: Date;

     @f.validator(validator.Email) email: string;

     @f.validator(validator.Positive) logins: number;
}
```


3. Put all as decorators (I don't like that at all)


```typescript
import {f, NoInTheFuture, Email, Positive} from 'marshal';

class User {
     @f @NoInTheFuture() birthdate: Date;

     @f @Email() email: string;

     @f @Positive() logins: number;
}
```

Any other idea? I like the 1. the most, but I'm not sure yet if that's a better way.

**Comment by chuyik** [comment]
Thanks for the reply! I think the 1 is more easier to type and unlikely to conflict with current methods.

With 1 I think of these API styles:

## validator groups

We could group the decorators with `@f.number` / `@f.date` / `@f.string` like:

```ts
import {f} from 'marshal';

class User {
    @f.number.positive()
	@f.number.min(3)
	@f.number.max(5)
	logins: number;

	@f.string.match(/a+/)
    @f.string.contains(/date/)
	@f.string.maxLength(10)
    username: string;
}
```

This one looks neat, but it may conflict with current method like `@f.array`.

## validator chaining

Like `Joi`, we could organize the validators in method chaining style, for example:

```ts
import {f} from 'marshal';

class User {
    @f.positive().min(3).max(5)
	logins: number;

	// with `string` prefix
	@f.string.match(/a+/).contains(/date/).maxLength(10)
    username: string;
}
```

The chaining style is easier to type but the first one is maybe more easier to write test and maintain.

**Comment by zhonghuiping** [comment]
Hi @marcj, this library  is very helpful to us, how did you plan to support this feature？ i agree  validator mode like Joi.

**Comment by marcj** [comment]
The Joi approach has been [implemented](https://github.com/deepkit/deepkit-framework/blob/master/packages/type/tests/validation-decorator.spec.ts). Additional validators can be easily added to the [library itself](https://github.com/deepkit/deepkit-framework/blob/master/packages/type/src/validation-decorator.ts).
