### ISSUE TITLE
(De)Serialize external class

### ISSUE THREAD

**Issue by lionelhorn** [deepkit/deepkit-framework#51]
How to deserialize from json and recreate a class instance from an external class definition?

Let's consider an external Timestamp class that I don't control:
With 2 constructor args: s and n.

```js
export class Timestamp {
   constructor(s: number, n: number);

   static now(): Timestamp;
   static fromDate(date: Date): Timestamp;
   static fromMillis(milliseconds: number): Timestamp;
   
   private readonly seconds: number;
   private readonly nanoseconds: number;
   
   toDate(): Date;
   toMillis(): number;
   isEqual(other: Timestamp): boolean;
   valueOf(): string;
}
```

So far I have something along the lines of:
```js
   const schema = createClassSchema(Timestamp);
   schema.addProperty("seconds", f.type(Number));
   schema.addProperty("nanoseconds", f.type(Number));

   const json = localStorage.getItem("timestamp");
   const obj = JSON.parse(json);
   const objWithTimestamp = plainToClass(ObjWithTimestamp, obj);
```

I've seen in the doc that you can decorate method props but I didn't see how to do it for external classes programatically (without decorators)

I've only seen an internal method like and tried
``` js
   const s = schema.getOrCreateMethodProperties("s");
   const n = schema.getOrCreateMethodProperties("n");
```

But then I couldn't figurate how to indicate Marshal ts to use the seconds, nanoseconds and map s,n param names as arguments.

How can I achieve that? If it's possible, could you hint me in the right direction ?

Related to #36

**Comment by marcj** [comment]
Unfortunately, that's not directly implemented in the `Schema` API, but you can work around that:

```

test('external Class', () => {
    class Timestamp {
        seconds: number = 0;
        nanoseconds: number = 0;

        constructor(s: number, n: number) {
            this.seconds = s;
            this.nanoseconds = n;
        }
    }

    const schema = createClassSchema(Timestamp);

    f.type(Number).asName('seconds')(schema.classType, 'constructor', 0);
    f.type(Number).asName('nanoseconds')(schema.classType, 'constructor', 1);

    expect(schema.getProperty('seconds').type).toBe('number');
    expect(schema.getProperty('nanoseconds').type).toBe('number');

    const timestamp = plainToClass(Timestamp, {seconds: 123, nanoseconds: 5});

    expect(timestamp.seconds).toBe(123);
    expect(timestamp.nanoseconds).toBe(5);
});

```

We can improve the `Schema` API by adding a `addMethodProperty` method as well.

**Comment by lionelhorn** [comment]
Thanks for the reply.

So If I understand your snippet correctly, you use the order of arguments in the constructor?

Adding `addMethodProperty` would be nice.

**Comment by marcj** [comment]
> So If I understand your snippet correctly, you use the order of arguments in the constructor?

`f.type(Number).asName('seconds')(schema.classType, 'constructor', 0);` last argument is the order.

> Adding addMethodProperty would be nice.

Yes, already added. Will be released with the first super-hornet release.

**Comment by marcj** [comment]
This is added in latest @deepkit/type release.
