### ISSUE TITLE
Error occurred when using is<InstanceType<typeof Person>> for type checking

### ISSUE THREAD

**Issue by uinz** [deepkit/deepkit-framework#563]
An error occurred when running the following code:

```ts
import { is } from "@deepkit/type";

class Person {
  constructor(readonly name: string, readonly age: number) {}
  sayHi() {
    console.log(
      `Hello, my name is ${this.name} and I am ${this.age} years old.`
    );
  }
}

const obj: unknown = {
  name: "bob",
  age: 13,
};

if (is<InstanceType<typeof Person>>(obj)) {
  obj.sayHi();
}
```

The error message is `TypeError: obj.sayHi is not a function`.

I'm just reporting an issue, I don't have any clear preference on the behavior of this code

package.json
```json
{
  "devDependencies": {
    "@deepkit/type-compiler": "1.0.1-alpha.143",
    "typescript": "5.4.4"
  },
  "dependencies": {
    "@deepkit/type": "1.0.1-alpha.143"
  }
}
```

**Comment by marcj** [comment]
the correct code is `if (is<Person>(obj)) {`

**Comment by uinz** [comment]
Yes, I know `is<Person>` is works fine.

However, in terms of type, `InstanceType<typeof Person>` and `Person` should be equivalent.

**Comment by marcj** [comment]
`typeof` is generally unsupported since it is technically not possible to cover this feature in its full way without increasing substantially the emitted JS code/bundle size.

**Comment by s97712** [comment]
Can typeof be partially implemented? At least supporting built-in types like Parameters, ConstructorParameters, ReturnType, and InstanceType would cover a wide range of use cases.

**Comment by s97712** [comment]
`typeof` is usually used with `infer`. If only the inferred part is emitted, wouldn't it be possible to avoid significantly increasing the code package size?
