### ISSUE TITLE
MessagePack

### ISSUE THREAD

**Issue by Uzlopak** [deepkit/deepkit-framework#60]
Do you plan to implement a messagepack package? Do you have a "template" or a recommendation for a package, where i could start to implement messagepack?

Best Regards
Uzlopak

**Comment by marcj** [comment]
Not yet. Marshal is all about performance, so the parser/serializer algo depends on the protocol/serialization format itself. For example class to mongo types works totally different than class to bson types. I just checked the spec: https://github.com/msgpack/msgpack/blob/master/spec.md - definitely more complex than BSON but shouldn't be that hard. Would look then the same as https://github.com/super-hornet/super-hornet.ts/blob/master/packages/marshal-bson/src/bson-parser.ts and https://github.com/super-hornet/super-hornet.ts/blob/master/packages/marshal-bson/src/bson-jit-parser.ts. Currently for the RPC API we use JSON as serialization format, but I thought about switching to BSON since its way faster. Would be interesting if a Marshal JIT msgpack parser beats BSON. I'm not about that, but looking at the code of [msgpack-javascript](https://github.com/msgpack/msgpack-javascript/blob/master/src/Decoder.ts) a Marshal JIT based parser using fixed schemas will definitely be faster.

**Comment by Uzlopak** [comment]
I benchmarked most of the message pack implementations and all of them are 10-100x slower than buffered JSON. The msgpack-javascript is also very slow.

We currently use Buffer.from(JSON.stringify(data)) and JSON.parse(data.toString()) for our intra service communication. At one point I tried to implement BSON in our code, and as you researched yourself, the standard implementations are 4-5x slower than buffered JSON.

BSON has the drawback, that you can(!) get in issues, if e.g. a key is starting with a $-sign and you also suddenly have to handle  ObjectIds in other services (:D)

**Comment by marcj** [comment]
@Uzlopak interesting. I thought msgpack-js was generally faster. Do you have the source code of your benchmarks still?

>  At one point I tried to implement BSON in our code, and as you researched yourself, the standard implementations are 4-5x slower than buffered JSON.

Yeah, you can use marshal-bson then, which is up to 3x faster than JSON.parse and buffered JSON.stringify. But that requires you to provide a schema.

> BSON has the drawback, that you can(!) get in issues, if e.g. a key is starting with a $-sign and you also suddenly have to handle ObjectIds in other services (:D)

I don't understand the issue/drawback here to be honest. `$` is not an issue in keys and well ObjectIds will be the same on both ends? Not sure what the issue is here.

**Comment by Uzlopak** [comment]
to 1: When I am back home, I will post my simple benchmark script ;).

to 2: Actually I would prefer schemaless transformation. We have unfortunately not very strict return values, maybe when we make our next major release.

to 3: In our product, we expect actually that our mongoIds are strings, when they come back from the Rpc-method. We will release our product in about 3 weeks, so we can not risk of breaking our product now. I wished we know the things we know now  about 10 months ago. ;).

**Comment by marcj** [comment]
1. cool.

2. Then msgpack-javascript is the fastest you get. The perf boost from JIT comes from "Fast properties" in v8. As soon as you handle those generically v8 disables fast object properties. Although there are some low hanging fruits like `getUint8` is slower than buffer[] in the js code for msgpack, it will never be as fast as a JIT function with fast property access.

3. nice, marshal-bson parses objectIds as strings as well, so you don't get ObjectId but a string when parsing the BSON.

**Comment by Uzlopak** [comment]
```
var msgpack = require("./build")

var os = require('os');

console.log(" OS: " + os.type() + " " + os.release() + " (" + os.arch() + ")");
console.log("RAM: " + os.totalmem() / 1048576 + " MB (total), " + os.freemem() / 1048576 + " MB (free)");
console.log("CPU: " + os.cpus()[0].speed + " MHz " + os.cpus()[0].model);

var obj = "test";

for (var r = 1; r < 4; r++) {
    console.log("\nRun #" + r + ":");
    var start = Date.now();
    for (var i = 0; i < 500000; i++) {
        msgpack.encode(obj);
    }
    var stop = Date.now();
    console.log("\t      MSGPACK: " + (stop - start) + " ms");

}

for (var r = 1; r < 4; r++) {
    console.log("\nRun #" + r + ":");
    var start = Date.now();
    for (var i = 0; i < 500000; i++) {
        JSON.stringify(obj);
    }
    var stop = Date.now();
    console.log("\t      JSON: " + (stop - start) + " ms");

}

```

results in:

```
Uzlopak@Battlestation:~/Workspace/msgpack-js$ node bench.js
 OS: Linux 5.7.1-050701-generic (x64)
RAM: 32115.39453125 MB (total), 23819.73828125 MB (free)
CPU: 802 MHz AMD Phenom(tm) II X6 1055T Processor

Run #1:
              MSGPACK: 2572 ms

Run #2:
              MSGPACK: 2449 ms

Run #3:
              MSGPACK: 2448 ms

Run #1:
              JSON: 72 ms

Run #2:
              JSON: 76 ms

Run #3:
              JSON: 68 ms
```

Somehow my self written JSON.stringify method is in most cases faster than the internal v8 JSON.stringify method. But when i want to write it to directly to buffer instead of strings, it gets extremely slow, so I guess, I use the worst approach to write buffers. :/

**Comment by marcj** [comment]
What is `msgpack-js` and `./build`?

**Comment by marcj** [comment]
I get with [msgpack-javascript](https://github.com/msgpack/msgpack-javascript)

```
➜ node bench
 OS: Darwin 19.5.0 (x64)
RAM: 32768 MB (total), 686.5859375 MB (free)
CPU: 2900 MHz Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz

Run #1:
	      MSGPACK: 426 ms

Run #2:
	      MSGPACK: 392 ms

Run #3:
	      MSGPACK: 394 ms

Run #1:
	      JSON: 38 ms

Run #2:
	      JSON: 39 ms

Run #3:
	      JSON: 36 ms
```

**Comment by marcj** [comment]
Btw you forgot to build a buffer with JSON.stringify.

Here the fixed benchmark + the string serializer that Marshal-BSON uses:

```
➜ node bench
 OS: Darwin 19.5.0 (x64)
RAM: 32768 MB (total), 652.3984375 MB (free)
CPU: 2900 MHz Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz

Run #1:
	      MSGPACK: 423 ms

Run #2:
	      MSGPACK: 386 ms

Run #3:
	      MSGPACK: 394 ms

Run #1:
	      JSON: 125 ms

Run #2:
	      JSON: 130 ms

Run #3:
	      JSON: 116 ms

Run #1:
	      custom: 42 ms

Run #2:
	      custom: 41 ms

Run #3:
	      custom: 38 ms
```


<details>
```
var msgpack = require("./dist")

var os = require('os');

console.log(" OS: " + os.type() + " " + os.release() + " (" + os.arch() + ")");
console.log("RAM: " + os.totalmem() / 1048576 + " MB (total), " + os.freemem() / 1048576 + " MB (free)");
console.log("CPU: " + os.cpus()[0].speed + " MHz " + os.cpus()[0].model);

var obj = "test";

for (var r = 1; r < 4; r++) {
    console.log("\nRun #" + r + ":");
    var start = Date.now();
    for (var i = 0; i < 500000; i++) {
        msgpack.encode(obj);
    }
    var stop = Date.now();
    console.log("\t      MSGPACK: " + (stop - start) + " ms");

}

for (var r = 1; r < 4; r++) {
    console.log("\nRun #" + r + ":");
    var start = Date.now();
    for (var i = 0; i < 500000; i++) {
        Buffer.from(JSON.stringify(obj));
    }
    var stop = Date.now();
    console.log("\t      JSON: " + (stop - start) + " ms");

}


function writeString(str, buffer) {
  let offset = 0;
  for (let i = 0; i < str.length; i++) {
    const c = str.charCodeAt(i);
    if (c < 128) {
        buffer[offset++] = c;
    } else if (c > 127 && c < 2048) {
        buffer[offset++] = (c >> 6) | 192;
        buffer[offset++] = ((c & 63) | 128);
    } else {
        buffer[offset++] = (c >> 12) | 224;
        buffer[offset++] = ((c >> 6) & 63) | 128;
        buffer[offset++] = (c & 63) | 128;
    }
  }
}

function stringByteLength(str) {
  if (!str) return 0;
  let size = 0;
  for (let i = 0; i < str.length; i++) {
    const c = str.charCodeAt(i);
    if (c < 128) size += 1;
    else if (c > 127 && c < 2048) size += 2;
    else size += 3;
  }
  return size;
}


for (var r = 1; r < 4; r++) {
    console.log("\nRun #" + r + ":");
    var start = Date.now();
    for (var i = 0; i < 500000; i++) {
        const buffer = Buffer.alloc(stringByteLength(obj));
        writeString(obj, buffer);
    }
    var stop = Date.now();
    console.log("\t      custom: " + (stop - start) + " ms");

}
```
</details>

**Comment by Uzlopak** [comment]
Would it not make more sense to test in the last case JSON.stringify(obj)?

Is the marshal string serializer always faster than Buffer.from???

**Comment by marcj** [comment]
> Would it not make more sense to test in the last case JSON.stringify(obj)?

The second tests already JSON.stringify. Why should the last test the same? 

> Is the marshal string serializer always faster than Buffer.from???

No, for bigger strings it gets slower.
