### ISSUE TITLE
ORM adapter for LibSQL

### ISSUE THREAD

**Issue by ansarizafar** [deepkit/deepkit-framework#610]
LibSQL https://github.com/tursodatabase/libsql is a fork of SQL ite
There are also various improvements and extensions to the core SQLite https://github.com/tursodatabase/libsql/blob/main/libsql-sqlite3/doc/libsql_extensions.md

LibSQL is also used by Turso https://turso.tech/ which has become very popular.  Please consider adding an ORM adapter for LibSQL.

**Comment by marcj** [comment]
We don't add VC financed libraries to our core, since they stop existing as soon as they run out of money (which is very likely)
