### ISSUE TITLE
@deepkit/type deserialize() doesn't throw in a wrapper

### ISSUE THREAD

**Issue by f3oall** [deepkit/deepkit-framework#616]
When I use a wrapper function, `ValidationError` is not thrown when properties are missing.

Created a repo with reproduction: https://github.com/f3oall/deepkit-deserialization

Run `bun test`, all tests should pass (but they don't). See comments in the test file for additional info.

**Comment by f3oall** [comment]
Might get it wrong, should `deserialize()` throw an error if there's missing required properties?

**Comment by marcj** [comment]
deserialize does not do any validation. use `cast` which does deserialize + validation https://github.com/deepkit/deepkit-framework/blob/ab96f2f3c0f7f795692d49e6a37ee5194647a9c1/packages/type/src/serializer-facade.ts#L26

**Comment by f3oall** [comment]
Gotcha, thanks!
