### ISSUE TITLE
Support for marshal.ts

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#63]
We were using marshal.ts before, what is the plan going forward with this project, is it still something supported? Is there documentation for marshal.ts still available?

Thanks

**Comment by marcj** [comment]
> is it still something supported

Absolutely. Marshal is the very core of this framework, and makes all of that possible. So it definitely will be around for a long time. It's named meanwhile `@deepkit/type` and has many more features and performance improvements. Will be released together with a new docu, website, and the whole framework soon.

> Is there documentation for marshal.ts still available?

Yes, documentation of marshal is still here https://marshal.marcj.dev/.

**Comment by ukarlsson** [comment]
Thanks! It may be good to link to the docs somewhere :)

**Comment by marcus-sa** [comment]
@marcj is `@deepkit/type` gonna be published to NPM anytime soon?

**Comment by marcj** [comment]
@marcus-sa yes. I think in one or two weeks already I'm going to publish the first beta.

**Comment by ukarlsson** [comment]
Ok looking forward to trying the beta. Is it compatible in terms of API with marshal.ts or will it require changes except switching the package?

**Comment by marcj** [comment]
@ukarlsson There are a couple of name changes, but nothing too dramatic.

**Comment by ukarlsson** [comment]
Hello, I saw that there is an alpha. Is it possible to use deepkit-framework instead of marshal.ts now?

**Comment by marcj** [comment]
@ukarlsson yes, it is useable now. Working at the moment on the new website including documentation, so until then you're on your own, although it's not fundamentally different to Marshal's API, so its documentation might help still. For the remaining stuff you should look at the type definitions, I tried to add more docblocks.

**Comment by marcj** [comment]
> How is the stability of @deepkit/type versus marshal.ts, would it be ready to use? :)

@deepkit/type is much more stable since we added more tests and bug-fixes meanwhile that Marshal did not get.

**Comment by ukarlsson** [comment]
Thanks, we are trying to migrate to it now!

**Comment by Rush** [comment]
@marcj one of the maintainers of Nest recommended `@deepkit/type` to me. Let's get rid of `class-transformer` :)

**Comment by marcj** [comment]
I think every was covered in this issue, so I'm closing it.
