### ISSUE TITLE
Support for @Transform

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#64]
In class-transformer, we have been using the `@Transform()` annotation to patch jsonb objects when we parse them from Postgres to facilitate migrations, for example adding default values for new fields. Is there anything similar in marshal.ts or deepkit? Thanks :)

**Comment by marcj** [comment]
What exactly do you patch here? What you can do is create your own postgres serializer by forking the json-serialize and change then certain properties/types automatically. Can you post your code so I can take a look at what you are doing exactly?

**Comment by ukarlsson** [comment]
Thanks for the reply! For example we ended up with NaN values by accident that we wanted to replace with undefined, then we also had numbers that sometimes were written to database as strings, in these cases we used class-transformer to transform these invalid to correct values before passing them to the application

```
class Stats {
  @Transform(v => removeNaN(v ?? undefined))
  @IsOptional()
  @IsNumber()
  public score?: number
  ...
  @Transform((id: number | string) => (typeof id === 'string' ? parseInt(id) : id))
  @IsInt()
  public id: number
  ...
}
```

**Comment by marcj** [comment]
I see. The thing is that with Deepkit you won't have NaN or strings when you defined those as number. It is automatically converted and validated, so there is at least for that use-case no need for a `Transform` modifier. I designed the library very carefully so that such dirty workarounds are not needed.

**Comment by ukarlsson** [comment]
Ok, we will solve these hacks that we need to do in other ways!
