### ISSUE TITLE
Marshal question - complex objects

### ISSUE THREAD

**Issue by vany0114** [deepkit/deepkit-framework#65]
Hi,

I'm using the marshal package (which is awesome btw) and I have this case, the issue I'm running into is that when deserializing I'm not getting the child objects as class instances but as anonymous types, so when I try to get for example: `simpleModel.foo.x` 
I'm getting an error because `foo` and `bar` are plain data, so at runtime, I see: `simpleModel.props.foo.props.x`

```
class BaseClass {
    @f.any() 
    protected props: T;

    constructor(props: T) {
        this.props = props;
    }
}

interface SimpleModelProps {
  foo: SubModel;
  bar: SubModel;
}

interface SubModelProps {
  x: number;
  y: Date;
}

class SubModel {
    constructor(props: SubModelProps) {
        this.props = props;
    }

    public get x(): number {
        return this.props.x;
    }

    public get y(): Date {
       return this.props.y;
    }
}

class SimpleModel extends BaseClass {    

     public get foo(): SubModel {
         return this.props.foo;
     }

     public get bar(): SubModel {
         return this.props.bar;
     }

    constructor(props: SimpleModelProps) {
        super(props);
    }
}
```

Any idea of what it's wrong with my code?

Thanks in advance!

**Comment by marcj** [comment]
Yeah, you use `f.any` which does not transform any data to class instances. You need to annotate what should be converted as the JSON data itself does not provide this information. Also a structure like `constructor(props: SubModelProps) {` is not well designed API if you ask me.

A better approach that has the same API except for constructing it:

```typescript
class SubModel {
     constructor(
         @f public readonly x,
         @f public readonly y,
     ) {}
}

class SimpleModel {
    constructor(
        @f public readonly foo: SubModel,
        @f public readonly bar: SubModel,
    ){}
}
```
