### ISSUE TITLE
Errors thrown do not extend Error

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#66]
Hello Marc! I am excited to try out the new version of Marshal. This is an issue we also had with the previous version that sometimes made it a bit difficult to work with!

In `validatedDeserialize` we have this code
```
    validatedDeserialize(data, options) {
        const errors = validation_1.validate(this.schema, data);
        if (errors.length)
            throw new validation_1.ValidationFailed(errors);
        if (!this._deserialize)
            this._deserialize = jit_1.getXToClassFunction(this.schema, this.serializer);
        return this._deserialize(data, options);
    }
```

The `ValidationFailed` class is defined as follows

```
export declare class ValidationFailed {
    readonly errors: ValidationFailedItem[];
    constructor(errors: ValidationFailedItem[]);
}
```

The class does not extend Error, and this breaks stacktrace reporting when I use express.js, for example I often see

```
[ERROR] 09:30:24 Error: uncaughtException [object Object]
```

Thanks!

**Comment by marcj** [comment]
Thanks for the report! should be fixed now in alpha4

**Comment by ukarlsson** [comment]
Thanks!
