### ISSUE TITLE
Problem with nullable properties that have class type

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#68]
Hey Marc! In the following code I try to mark a member as nullable, but we get some errors

```
class ExampleClass {}

class ConstructorClass {
  constructor(
    @(f.type(ExampleClass).nullable)
    public klass1: ExampleClass | null,
    @(f.type(ExampleClass).optional.nullable)
    public klass2: ExampleClass | null
  ) {}
}
```

This is the error

```
Error: ConstructorClass::constructor::klass2 type mismatch. Given ExampleClass, but declared is Object or undefined. The actual type is an object, but you specified a class in @t.type(T).
Please declare a type or use @t.map(ExampleClass) for 'klass2: {[k: string]: ExampleClass}'.
    at /home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/$$virtual/@deepkit-type-virtual-2dd13a0eb3/0/cache/@deepkit-type-npm-1.0.0-alpha.5-debcd2ddae-bfd4da2d98.zip/node_modules/@deepkit/type/src/decorators.ts:2358:19
    at fn (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/$$virtual/@deepkit-type-virtual-2dd13a0eb3/0/cache/@deepkit-type-npm-1.0.0-alpha.5-debcd2ddae-bfd4da2d98.zip/node_modules/@deepkit/type/src/decorators.ts:1849:9)
    at /home/ulf/sana-sierra-mono-1/lerna-project-root/domain/marshal-test.ts:12:37
    at DecorateConstructor (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/cache/reflect-metadata-npm-0.1.13-c525998e20-629101e6c8.zip/node_modules/reflect-metadata/Reflect.js:541:33)
    at Object.decorate (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/cache/reflect-metadata-npm-0.1.13-c525998e20-629101e6c8.zip/node_modules/reflect-metadata/Reflect.js:130:24)
    at __decorate (/home/ulf/sana-sierra-mono-1/lerna-project-root/domain/marshal-test.ts:4:92)
    at Object.<anonymous> (/home/ulf/sana-sierra-mono-1/lerna-project-root/domain/marshal-test.ts:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/home/ulf/sana-sierra-mono-1/lerna-project-root/.yarn/$$virtual/ts-node-virtual-460cd590c0/0/cache/ts-node-npm-9.0.0-7f58a021c2-49d2ab087f.zip/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

```

I also don't really understand how `.optional` and `.nullable` interact. We basically have two cases

1. we deserialize objects and some property can be `undefined` in the database
2. we deserialize objects and some property can be `nullable` in the database

It is always either 1 or 2. What options should we use? It would be good to be strict so we can use

```
public property: T | undefined
```
when it is undefined and

```
public property: T | null
```
when it can be null.

Many thanks

**Comment by marcj** [comment]
Good catch. Indeed we rarely work with nullable as its discouraged even by the TypeScript team. However I fixed the reported error, making your use-case workable as intended.

The correct definition is:

```typescript
@t.nullable
public property: T | null = null;


@t.optional
public property?: T;

@t.optional
public property: T | undefined = undefined;
```

**Comment by marcj** [comment]
Available in alpha6. However, I'd recommend to use the .optional approach:

```typescript
class ConstructorClass {
  constructor(
    @f.type(ExampleClass).optional
    public klass1?: ExampleClass,
    
    @f.type(ExampleClass).optional)
    public klass2?: ExampleClass
) {}
}
```

Makes it cleaner IMHO and more aligned with JS/TypeScript philosophie (as null is rarely used in JS anways)

**Comment by ukarlsson** [comment]
Thanks for the fix, we will try to move towards undefined! Right now we have an issue since we have a bit mixed data in the database (using class-transformer before and it was pretty sloppy on this undefined/nullable). So we need to always apply a default value regardless of whether it is `null` or `undefined`.

It seems like deepkit only applies `.default()` to either `null` or `undefined` for example 

```
class TestClass {
  constructor(
    @f.type(Number).optional.nullable.default(1.0)
    public v1?: number | null
  ) {}
}

console.log(jsonSerializer.for(TestClass).validatedDeserialize({
  v1: undefined
}))

console.log(jsonSerializer.for(TestClass).validatedDeserialize({
  v1: null
}))

console.log(jsonSerializer.for(TestClass).validatedDeserialize({
  v1: 3.14
}))
```
yields output
```
TestClass { v1: 1 }
TestClass { v1: null }
TestClass { v1: 3.14 }
```
Would it make sense to apply `.default()` to both `null` and `undefined` like class-transformer did?

Many thanks :)

**Comment by marcj** [comment]
If the field is nullable and you overwrite the setter to apply the default value when null is given, then you never end up having null as property value. Thus you should probably remove the |null type, shouldn't you?

**Comment by ukarlsson** [comment]
Thanks for quick response!

I have applied both `.optional` and `.nullable` here, and then when I decode from Json I would like both null and undefined to be converted to 1.0 using the default value above.

**Comment by marcj** [comment]
As alternative, you can fork the jsonSerializer and add that nullable rule on your own. Here is a test code that uses the jsonSerializer and forks it implementing your use-case:

```typescript
test('null as default value', () => {
    class TestClass {
        constructor(
            @t.type(Number).optional.nullable.default(1.0)
            public v1?: number | null
        ) {}
    }

    const testClassSerializer = jsonSerializer.for(TestClass);

    expect(testClassSerializer.validatedDeserialize({v1: undefined})).toEqual({v1: 1.0});
    expect(testClassSerializer.validatedDeserialize({v1: null})).toEqual({v1: null});
    expect(testClassSerializer.validatedDeserialize({v1: 3.14})).toEqual({v1: 3.14});

    const myDbSerializer = new class extends jsonSerializer.fork('my-db-serializer') {
    };
    myDbSerializer.toClass.register('null', (property, compiler) => {
        compiler.addSetter(compiler.setVariable('value', property.defaultValue));
    });

    const testClassDbSerializer = myDbSerializer.for(TestClass);

    expect(testClassDbSerializer.validatedDeserialize({v1: undefined})).toEqual({v1: 1.0});
    expect(testClassDbSerializer.validatedDeserialize({v1: null})).toEqual({v1: 1.0});
    expect(testClassDbSerializer.validatedDeserialize({v1: 3.14})).toEqual({v1: 3.14});
});
```

**Comment by marcj** [comment]
>  If I remove the | null does not seem to have any effect as far as I can see

I won't, as there is no code in the jsonSerializer that automatically converts `null` to a default value. I'm not sure if this is expected behavior. For `undefined` it surely is, as that is how Javascript works. But null is never converted to a default value in Javascript, so I'd like to stick with that convention.

**Comment by ukarlsson** [comment]
Ok, the forked serializer like above seems perfect! We will try to migrate all the existing data going forward  to use undefined instead of null and I agree that the current implementation makes sense! :)
