### ISSUE TITLE
Default value for Date not parsed

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#70]
Hello, found an issue with default values for Date

```
class DateClass {
  constructor(
    @f.type(Date).optional.default('2019-11-03T09:10:38.392Z')
    public value: Date,
  ) {}
}

console.log(jsonSerializer.for(DateClass).validatedDeserialize({
  value: '2020-11-03T09:10:38.392Z',
}))

console.log(jsonSerializer.for(DateClass).validatedDeserialize({
}))
```
This yields output
```
DateClass { value: 2020-11-03T09:10:38.392Z }
DateClass { value: '2019-11-03T09:10:38.392Z' }
```

It seems a bit problematic to use a string as default also if we want to change the serializer to serialize the dates in a different way

**Comment by marcj** [comment]
That's correct behavior as the argument of `default` is not parsed, but used as is. You should use instead:

```typescript
@f.type(Date).optional.default(new Date('2019-11-03T09:10:38.392Z'))
```

**Comment by marcj** [comment]
Btw, I don't know why you use always optional constructor arguments, but a better API would be this:


```typescript
class DateClass {
   @f.optional
   public value: Date = new Date('2019-11-03T09:10:38.392Z');
}
```

or if it really should be in the constructor

```typescript
class DateClass {
   constructor(
     @f.optional public value: Date = new Date('2019-11-03T09:10:38.392Z')
  ) {}
}
```

**Comment by ukarlsson** [comment]
Ok thanks! Right, this seems to work when I pass `new Date()`!

The default constructor parameter does not work with babel when I also use `@f` annotations, I get errors like this when we build with next.js. It seems hard to understand why

```
Property name expected type of string but got null
```

**Comment by marcj** [comment]
That's weird, a decorator should not change the data type of the property. Can you provide a reproduction code? I don't use Babel to quickly create a reproduction myself. Do you use the newest version of babel etc?

**Comment by marcj** [comment]
I'm going to close this since no response.
