### ISSUE TITLE
[type] registerConverterCompiler

### ISSUE THREAD

**Issue by anton-johansson** [deepkit/deepkit-framework#87]
I was looking through documentation of a package:
https://marshal.marcj.dev/

There I can see that it has support for custom type converters (`registerConverterCompiler`), so I can register converters myself. However, when browsing a bit, I found that the package is superseded by this package! Looks a lot more structured, very nice, however I can't seem to find this registration function. Is this no longer supported?

**Comment by marcj** [comment]
Yes, that still works. In fact it got a lot more modular. What is your use-case exactly? If you tell more about what you are planning to do I can provide you examples.

**Comment by anton-johansson** [comment]
Thanks for the reply!

For example, when marshalling and unmarshalling between plain objects and my classes, I want types like `LocalDate` and `LocalDateTime` (I'm using `js-joda`) to be written/parsed to/from strings, using my own format.

**Comment by marcj** [comment]
I'll leave this example and close this issue as there is nothing to do:

https://github.com/deepkit/deepkit-framework/blob/master/packages/type/tests/serializer-api.spec.ts#L47-L65
