### ISSUE TITLE
Missing main property in package.json

### ISSUE THREAD

**Issue by marcus-sa** [deepkit/deepkit-framework#88]
The `@deepkit/core` and `@deepkit/type` packages are missing the `main` property in their `package.json` causing it to fail when importing in a Node environment.

```json
{
  "main": "./dist/cjs/index.js"
}
```
Currently using them in https://github.com/marcus-sa/nest-convoy

**Comment by marcj** [comment]
Which version do you use? Current version do contain `main` correctly, just verified.

**Comment by marcus-sa** [comment]
Ah okay, I'm using `1.0.1-alpha.12`

**Comment by marcj** [comment]
Time to upgrade I'd say

**Comment by marcus-sa** [comment]
Wop
