### ISSUE TITLE
Hyphenated class properties fail to validate

### ISSUE THREAD

**Issue by redappleorigin** [deepkit/deepkit-framework#93]
When using validate or validatePlainToClass, the hyphenated class property will have everything before the last hyphen stripped, causing validation to fail.

I came across the issue while trying to validate incoming request headers.

**Comment by marcj** [comment]
Yes, hyphens are not allowed, only valid javascript variable names are.

**Comment by marcj** [comment]
This is supported now in master with the new runtime type system
